### ISSUE TITLE
tray icon locked in red after upgrade on 5.1.1

### ISSUE THREAD

**Issue by dominix** [vladimiry/ElectronMail#557] opened 2022-09-24 03:13 UTC
Hi everyone,

I am running ubuntu Mate 22.04 and use electronMail for long time. 
Since uograde from 5.1.0 to 5.1.1 via snap, the application is till running but the tray icon do not reflect the application status. 
it do not display the yellow dot while login in, neither show if there is new mail ... which is annoying.

instead it stay red with a grey stop sign (not clear) but the menu stil is working so I can toggle windows to see inbox.

regards.

**Comment by dominix** [comment] 2022-09-24 03:30
please NB :  if I revert to 5.1.0 tray icon is back to normal. 
used command : "sudo snap revert  electron-mail"  
(first, stop the application ...)

**Comment by vladimiry** [comment] 2022-09-24 10:11
Looks like a dupe of https://github.com/vladimiry/ElectronMail/issues/555 (resolved by switching to flatpak package).

**Closed by vladimiry** 2022-09-24 10:11 UTC
