### ISSUE TITLE
Unable to print from email

### ISSUE THREAD

**Issue by flphotog** [vladimiry/ElectronMail#462] opened 2021-11-12 14:21 UTC
I've been unable to print from an email for at least the last 2 versions. Just tried the newest version and have the same problem. Electron-mail just crashes when trying to print. I've sent in a crash report.
This is something I use frequently so I'm forced back to the web version.
I've tried both the .deb and appImage on Ubuntu 20.04.
Linux carson-Aspire-A515-43 5.11.0-40-generic #44~20.04.2-Ubuntu SMP Tue Oct 26 18:07:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by vladimiry** [comment] 2021-11-12 14:27
Thanks for the report. I don't normally test printing before releasing, unfortunately. Unfortunately, @electron is well known for having recurring problems with printing (they fix it, and then it get back, and so on). So I believe there should already be an open issue in https://github.com/electron/electron/issues tracker (will link it here when/if I get it located).

> This is something I use frequently so I'm forced back to the web version.

The ugly workaround is to export emails to EML and print them using some program that is able to deal with EML.

**Comment by flphotog** [comment] 2021-11-12 14:37
Thanks, I did check open issues and didn't see one, but I could have missed it.

Carson Wilcox
***@***.***
GNU/Linux Ubuntu 20.04.2 LTS

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by vladimiry** [comment] 2021-11-12 14:44
By the way, consider trying the @electron v15 based build shared in https://github.com/vladimiry/ElectronMail/issues/460#issuecomment-966514321.

**Comment by vladimiry** [comment] 2021-11-16 11:43
@flphotog can you test the following builds?:
- Shared in https://github.com/vladimiry/ElectronMail/issues/460#issuecomment-966514321
- Shared in https://github.com/vladimiry/ElectronMail/issues/460#issuecomment-970189672

**Comment by vladimiry** [comment] 2021-11-18 08:51
Closing the issue as:
- No addition information provided.
- I was not able to reproduce the issue at my side (Linux). Also asked few user to test printing on Win 10 system and it also ok.

**Closed by vladimiry** 2021-11-18 08:51 UTC
Labels: upstream, crash, printing
