### ISSUE TITLE
Question: Tutanota search

### ISSUE THREAD

**Issue by charlag** [vladimiry/ElectronMail#97] opened 2019-01-21 08:02 UTC
Hello from the Tutanota team!

First of all, thanks for the impressive work. It is really great that Tutanota is growing an app infrastructure around it. I hope that we'll be able to make it easier in the future.

We had a question regarding search.
The way it works in official Tutanota client is that when enabling search, we build the search index. For that we have to download a lot of mails and mail bodies and this is a high server load. That's the main reason to restrict index building to two weeks for free users.

We wanted to ask if email-securely-app is doing something similar for it's search functionality and how it does build search index in general. Is it just intercepting incoing WebSocket events?

Thanks!

**Comment by charlag** [comment] 2019-01-21 12:43
Thankf for the thoughtful response.

Local database is, undoubtful, very important. We have offline usage [planned](https://tutanota.com/roadmap/). You can export emails as .eml files as well.

We have rate limiting, but it seems it's high enough that no one is hitting it.

The reason you cannot reach beginning of the event queue I think is that the server only stores last X event batches. You cannot hit 404 with request for multiple IDs, it just won't be in the list, if I remember correctly.

The process you sounds exactly like index building we're doing in the app. We just store data in a different form. Requests for multiple entities are among the most dangerous ones, because you can cause a lot of server load with one request. That's why we request 100 emails and 20 other entities at once. And perhaps we should enforce this better.

Thanks for the explanations again. I will discuss it with the team.

**Comment by vladimiry** [comment] 2019-01-21 13:06
> The reason you cannot reach beginning of the event queue I think is that the server only stores last X event batches. 

I remember I could perfectly process the queue from the beginning, ie reconstructing the full actual data state just going through the queue. Though the history of the account I was developing the feature with was relatively/very short. The issue is that just at some point system folders adding events just stopped being added to the queue or I agree maybe it was because the account hit a point after which outdated events just got removed from the queue, it makes sense to me. 

> You cannot hit 404 with request for multiple IDs, it just won't be in the list, if I remember correctly.

I remember I was able to get 404 errors somehow, but I was trying very hard to do so. Not sure, maybe at that time the app was fetching the entities executing individual requests but not the chunked requests like it currently does. Anyway, there is no actual issue here, but thanks for the hint.

> Requests for multiple entities are among the most dangerous ones, because you can cause a lot of server load with one request. That's why we request 100 emails and 20 other entities at once. And perhaps we should enforce this better.

To clarify this point. The app currently requests 100 entities in a chunk for any kind of entity and 50 entities in a chunk for body entity. The app fetches only needed/limited kinds of entities. I'm ready decreasing body entities chunk size if it helps.

**Comment by vladimiry** [comment] 2019-03-11 21:38
Closing as resolved.

**Closed by vladimiry** 2019-03-11 21:38 UTC
Labels: provider concern, question

**Comment by charlag** [comment] 2019-03-11 21:39
Sorry for not responding for so long. We would be glad if you decreased number of requested bodies down to 20 at a time. We have some ideas on how to optimize this so it can get bigger in the future.

**Comment by vladimiry** [comment] 2019-03-12 06:04
New version will include bodies chunk size value decreased from 50 to 20.

**Comment by vladimiry** [comment] 2019-03-12 14:53
> decreased number of requested bodies down to 20 at a time

https://github.com/vladimiry/ElectronMail/commit/0904249720edaf8df6cc0a3af9a379e7a853a4c3
