### ISSUE TITLE
Minor issue: HiDPI problem

### ISSUE THREAD

**Issue by leaxdc** [vladimiry/ElectronMail#225] opened 2019-12-30 10:13 UTC
Hi, there is small problem with HiDPI tray icon in Mac OS (screen is attached)

Configuration: MacOS Catalina / MacBook Pro 15" Retina

<img width="157" alt="Screenshot 2019-12-30 at 11 11 50" src="https://user-images.githubusercontent.com/2706884/71577729-939b3d00-2af5-11ea-9ce2-3b57a9acb7bc.png">

**Comment by leaxdc** [comment] 2019-12-30 10:14
<img width="157" alt="Screenshot 2019-12-30 at 11 11 50" src="https://user-images.githubusercontent.com/2706884/71577729-939b3d00-2af5-11ea-9ce2-3b57a9acb7bc.png">

**Comment by vladimiry** [comment] 2019-12-30 12:29
Closing as duplicate of #199

**Closed by vladimiry** 2019-12-30 12:29 UTC
