### ISSUE TITLE
ElectronMail stopped working for no apparent reason

### ISSUE THREAD

**Issue by PacoH** [vladimiry/ElectronMail#552] opened 2022-09-19 16:38 UTC
OS X Monterey
ElectronMail 5.1.0

I was replying to an email and all of a sudden there was no response. I had to force quit and when I reopened it same thing. I reinstalled it and same thing.

**Comment by vladimiry** [comment] 2022-09-20 08:51
The app remains static, so something got changed on your system or at the proton side.

> I reinstalled it and same thing.

You could also try removing everything from the [app settings folder](https://github.com/vladimiry/ElectronMail/blob/master/images/open-settings-folder.jpg) except for the following/app's files listed on the [FAQ](https://github.com/vladimiry/ElectronMail/wiki/FAQ):
- config.json (this one also can be removed as it will be re-created on app start with default values)
- settings.bin
- database.bin
- database-session.bin (this one also can be removed/renamed if the issue is still there)
- session.bin

**Comment by PacoH** [comment] 2022-09-20 14:58
Thank you Vladimiri. I forgot to mention that the app window does not even open, so I couldn't 'Open Settings Folder.' I found it though at `~/Library/Application Support/electron-mail`. I did what you said but no change. I deleted the whole directory and still no change. I undeleted the original directory and when I ran it, still no app window BUT there *was* a notification popup dialog announcing new emails. When I clicked it I got the app window and everything was back to normal. ???

**Comment by vladimiry** [comment] 2022-09-20 15:07
Sounds mysterious. I tend to think it's related to your system. Let's name it a glitch and close the issue if it got resolved at your side.

**Comment by PacoH** [comment] 2022-09-20 18:55
I found nothing in the system logs. Usually there will be a crash report in a case like this.

**Comment by vladimiry** [comment] 2022-11-04 12:59
I have no idea what could help with resolving the issue, at least having no additional information provided. So, closing for now.

**Closed by vladimiry** 2022-11-04 12:59 UTC
