### ISSUE TITLE
Flatpak -Wrong icon on systray

### ISSUE THREAD

**Issue by diogonr** [vladimiry/ElectronMail#317] opened 2020-08-20 17:08 UTC
OS: Pop OS 20.04
Version: com.github.vladimiry.ElectronMail 4.8.0 stable @ flatpak
DE: Gnome 3.36

On my system, the systray icon is just a generic electron icon
![image](https://user-images.githubusercontent.com/42862719/90803045-120c4f80-e310-11ea-8dfe-075804656668.png)
instead of being the icon shown on the tray
![image](https://user-images.githubusercontent.com/42862719/90803067-19cbf400-e310-11ea-84c1-c2b717146aba.png)

**Comment by vladimiry** [comment] 2020-08-20 17:29
> @ flatpak

Btw, do you experience #311 issue?

**Comment by dioio-io** [comment] 2020-08-20 17:31
> > @ flatpak
> 
> Btw, do you experience #311 issue?

I occasionally have to go to options and switch the API entry point

**Comment by dioio-io** [comment] 2020-08-25 19:45
The systray problem also occurs in snap variant

**Comment by Dvlnst** [comment] 2020-11-10 14:05
Are you using a custom icons theme? I had the same problem. In my case, it wasn't an ElectronMail's issue but my custom icons theme (Numix Circle). My theme was overwriting the ElectronMail with Electron icon due to naming.

As a workaround, I removed Electron default icon in my custom theme (installed system-wide):
```
$ sudo mv /usr/share/icons/Numix-Circle/48/apps/electron.svg /usr/share/icons/Numix-Circle/48/apps/electron.svg_backup
& sudo update-icon-caches /usr/share/icons/*
Restart ElerctronMail
```

So, I recommend you (if you are using a custom icons theme) to find where it's installed and try to remove the default Electron icon. I hope it helps.

Kind regards.

**Comment by kb8cb40j1av39c02** [comment] 2020-11-24 09:02
> Are you using a custom icons theme? I had the same problem. In my case, it wasn't an ElectronMail's issue but my custom icons theme (Numix Circle). My theme was overwriting the ElectronMail tray icon with Electron default icon due to naming.
> 
> As a workaround (works for me in snap and flatpak variants), I removed Electron default icon in my custom theme (installed system-wide):
> 
> ```
> $ sudo mv /usr/share/icons/Numix-Circle/48/apps/electron.svg /usr/share/icons/Numix-Circle/48/apps/electron.svg_backup
> $ sudo update-icon-caches /usr/share/icons/*
> Restart ElectronMail
> ```
> 
> So, I recommend you (if you are using a custom icons theme) to find where it's installed and try to remove the default Electron icon. I hope it helps.
> 
> Kind regards.

I can confirm this fix worked for me. My Iconpack contained several "electron.svg" icons. Deleting them fixed the tray icon.

**Comment by vladimiry** [comment] 2021-11-30 14:19
Closing the issue as the upstream one. The issue lies at the side of your system or the appearance theme you use. See #464 for details.

**Closed by vladimiry** 2021-11-30 14:19 UTC
Labels: upstream, workaround-exists, env-dependent, env: snap, env: flatpak
