### ISSUE TITLE
Electron mail needs to have the option for the stable protonmail v3.16.24.

### ISSUE THREAD

**Issue by Chummpp** [vladimiry/ElectronMail#297] opened 2020-06-05 13:38 UTC
Users only have the option to use the beta version of protonmail when we need to have the option to use the stable version as well. This should have been fixed along time ago.

**Comment by vladimiry** [comment] 2020-06-05 13:49
Closing as duplicate of #262.

**Closed by vladimiry** 2020-06-05 13:49 UTC
