### ISSUE TITLE
Glitch Icon macOS Catalina

### ISSUE THREAD

**Issue by Dev727** [vladimiry/ElectronMail#283] opened 2020-04-23 19:51 UTC
I installed this using both Homebrew and the official .dmg file. No matter which method, I seem to get a glitchy icon when using Spotlight. 

![IMG_20200423_144150](https://user-images.githubusercontent.com/37845033/80143052-d0da7d80-8571-11ea-8b15-8149ce0f49fc.jpg)

**Comment by vladimiry** [comment] 2020-04-23 20:29
Thanks for placing informative issue. Similar issue #185 was closed before as the issues is the upstream one and I'm closing this one with the same reasoning (also see #263). The issue is out of EM scope.

**Closed by vladimiry** 2020-04-23 20:29 UTC
