### ISSUE TITLE
ElectronMail stopped working today

### ISSUE THREAD

**Issue by mainetenants** [vladimiry/ElectronMail#605] opened 2023-04-04 13:50 UTC
When I opened ElectronMail desktop app today on my Ubuntu 22.04, it won't load my mail and instead throws this error. I exited the app, updated and upgraded my system in the terminal and started ElectronMail again, with the same results. 

Oops, something went wrong
There was a problem connecting to Proton.
Please refresh the page or check your connection.
Error: App version outdated

**Comment by vladimiry** [comment] 2023-04-04 13:52
Duplicate of #603.

**Closed by vladimiry** 2023-04-04 13:52 UTC
