### ISSUE TITLE
Invocation timeout of calling

### ISSUE THREAD

**Issue by codeduph** [vladimiry/ElectronMail#619] opened 2023-06-12 02:54 UTC
Invocation timeout of calling "notification" method on "electron-mail:webview-api:primary" channel with 25000ms timeout

![2023-06-12_104103](https://github.com/vladimiry/ElectronMail/assets/16449014/0207793a-8e78-418e-935d-0d1acd4ba23d)

issue in 2020 [ https://github.com/vladimiry/ElectronMail/issues/252 ] ??

**Comment by vladimiry** [comment] 2023-06-12 07:41
Dupe of #559.

**Closed by vladimiry** 2023-06-12 07:41 UTC
