### ISSUE TITLE
Cant open pdf attachments in the app.

### ISSUE THREAD

**Issue by zcsbarn** [vladimiry/ElectronMail#435] opened 2021-09-07 12:14 UTC
When I open PDFs in protonmail all it shows is a blank page.  This is frustrating as much as the work i do involves PDFs.  Electronmail is great otherwise!

![Screenshot Electronmail](https://user-images.githubusercontent.com/90257353/132342528-2c7cfdec-0fd3-459f-9849-c6d77a817ba6.png)

**Comment by vladimiry** [comment] 2021-09-07 12:19
Closing as duplicate of #371.

**Closed by vladimiry** 2021-09-07 12:19 UTC
