### ISSUE TITLE
cannot attach file: file manager Nemo issue in Cinnamon desktop environment

### ISSUE THREAD

**Issue by edmundlaugasson** [vladimiry/ElectronMail#375] opened 2021-02-24 13:53 UTC
When trying to add attachment and opening the default file manager nemo 4.8.4 in Cinnamon DE 4.8.6, then only Downloads folder is visible and no other folder in $HOME. So, cannot attach file. Only drag-and-drop is the way, how currently we can attach file, using Cinnamon DE and Nemo  in Linux Mint 20.1. Actually Desktop choice on navigation bar is visible, but desktop will NOT be opened and actually that Desktop choice on navigation bar cannot be activated. When trying manually via CTRL+L enter location, the window will be closed and no location will be opened.
EDIT: looks like even drag-and-drop to attach file doesn't work :( Only via that Downloads folder is currently still possible to attach file.

**Comment by vladimiry** [comment] 2021-02-24 14:04
Closing as duplicate of #324. Recap: this is by design (security measure).

**Comment by edmundlaugasson** [comment] 2021-02-24 14:05
Very "interesting" design...

**Closed by vladimiry** 2021-02-24 14:04 UTC

**Comment by vladimiry** [comment] 2021-02-24 14:13
The source code is open and clear enough. So it's quite possible to assembly your own package if necessary. As for defaults, it's about utilizing the flatpak capabilities of narrowing down the access rights to storage locations on the system the app is able to interact with which is considered good practice in terms of privacy/security.

**Comment by edmundlaugasson** [comment] 2021-02-25 23:56
Source code is for developers. I am not.
