### ISSUE TITLE
Electronmail is crashing

### ISSUE THREAD

**Issue by RobertKirchner9** [vladimiry/ElectronMail#612] opened 2023-04-20 02:44 UTC
When I open ElectronMail, it opens successfully, but then 10 seconds or so later it gives me a couple of error messages (screenshots attached) and then crashes. Running on Linux Mint Mate 21.1. 
![Screenshot at 2023-04-19 20-42-09](https://user-images.githubusercontent.com/36320249/233244640-5acf17af-a3de-4b79-bf7c-26e56026ef6c.png)
![Screenshot at 2023-04-19 20-42-31](https://user-images.githubusercontent.com/36320249/233244650-e5e8ce2c-77ff-456b-a0b9-3c9b9affdfe6.png)

**Comment by vladimiry** [comment] 2023-04-20 11:27
Closing as duplicate of #551.

Not a crash since the app keeps working. Disabling full-text search is a workaround.

There is a fallback "html to txt" conversion via iframe vs text-based processing, and I guess this is where the issue lies.

**Closed by vladimiry** 2023-04-20 11:27 UTC

**Comment by RobertKirchner9** [comment] 2023-07-02 20:20
I'm having repeated issues in recent days with Electronmail crashing about 30 seconds after opening.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by vladimiry** [comment] 2023-07-02 20:22
There was no app update in the recent days, so it's likely related to your system (some system updates, or installed uninstalled software/drivers/etc).

**Comment by vladimiry** [comment] 2023-07-02 20:24
You seem to run Linux, so consider running the app type other than crashing one. I'd recommend trying "containerized" package types first, like Flatpak or Snap, since those come with some system isolation capabilities.

**Comment by RobertKirchner9** [comment] 2023-11-16 23:57
When I try to open ElectronMail now, I get this error message.

> Something went wrong
> We couldn't load this page. Please refresh the page or check your internet connection.Error: App version outdated

I updated from v.5.2.1 to 5.2.2 but the problem persists.

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by vladimiry** [comment] 2023-11-17 00:00
> I updated from v.5.2.1 to 5.2.2 but the problem persists.

What is the direct link you got the update from? Still works fine at my side, so let's see if there will be more reports.

**Comment by RobertKirchner9** [comment] 2023-11-17 00:04
nvm, it's working now.

Sent with [Proton Mail](https://proton.me/) secure email.
