### ISSUE TITLE
ElectronMail 4.2.2 No Longer Displays ProtonMail UI

### ISSUE THREAD

**Issue by gourdcaptain** [vladimiry/ElectronMail#250] opened 2020-02-11 22:39 UTC
After launching ElectronMail 4.2.2 on Arch Linux today, it showed the ProtonMail login screen, filled in the password automatically and then resulted in a blank grey screen with no further progress instead of progressing to the one-time key screen. The Database view still works as normal. Attached is an image of what the resulting failure to load ProtonMail looks like:
![ElectronMail 4 2 2 - No ProtonMail UI](https://user-images.githubusercontent.com/7662067/74286283-6eedd400-4cf5-11ea-9fef-6e0533aa6cce.jpg)

**Comment by vladimiry** [comment] 2020-02-12 09:29
I'd like to clarify the issue. The app v4.2.2 worked well until recently but then just started showing gray screen or you just installed v4.2.2 and it shows you that gray screen from the first start? The first case would be a strange behavior since the app is a static thing.

Can you enable the `debug` log mode in "general" app settings block? Then restart the app and wait for the gray screen. Then send the log file to email specified [here](https://github.com/vladimiry/ElectronMail/blob/master/package.json#L5) (`log.log` file located in the [settings](https://github.com/vladimiry/ElectronMail/blob/master/images/open-settings-folder.jpg) folder).

**Comment by srappan** [comment] 2020-02-12 15:14
I'm having the same issue. Here's my debug log
[log.log](https://github.com/vladimiry/ElectronMail/files/4193057/log.log)

**Comment by vladimiry** [comment] 2020-02-12 15:24
@srappan you started facing the issue just recently or from the first v4.2.2 start?

**Comment by srappan** [comment] 2020-02-12 15:27
just recently.

**Comment by gourdcaptain** [comment] 2020-02-12 15:28
While I can't get the log until later today, I'd been using 4.2.2 successfully since it was released until yesterday around 5 PM EST when I closed it, rebooted my computer and it failed to work on launching it again.

-------- Original Message --------

**Comment by vladimiry** [comment] 2020-02-12 15:34
> just recently.

Weird stuff. I don't have a meaningful response yet.

> Deleted the entire settings folder and even after reconfiguring same issue

Can you try deleting the entire settings folder and installing the package from here https://github.com/vladimiry/ElectronMail/releases/tag/v4.2.2?

Also I'm interested to know if `electron-mail-4.2.2-linux-x86_64.AppImage` package works without the issues.

> Also running Arch

Can you show the `uname -a` output?

**Comment by vladimiry** [comment] 2020-02-12 18:01
By the way the work-in-progress v4.2.3 is uploaded [here](https://mega.nz/#F!ttQ3yahZ!rPPra4sbzpGxdHDiohH5-g) if someone wants to give it a try. It's the yesterday's build from the master branch. The diff [link](https://github.com/vladimiry/ElectronMail/compare/v4.2.2...da8d5e2187370b135f6dd037bf3bd81417ebd139). So not a lot of changes so far, but `@electron 7.1.10 => 8.0.0` bump is a major update which might potentially affect the app behavior.

**Comment by vladimiry** [comment] 2020-02-12 18:20
> Can you enable the debug log mode in "general" app settings block?

`verbose` mode should be enough.

**Comment by srappan** [comment] 2020-02-12 18:43
> By the way the work-in-progress v4.2.3 is uploaded [here](https://mega.nz/#F!ttQ3yahZ!rPPra4sbzpGxdHDiohH5-g) if someone wants to give it a try. It's the yesterday's build from the master branch. The diff [link](https://github.com/vladimiry/ElectronMail/compare/v4.2.2...da8d5e2187370b135f6dd037bf3bd81417ebd139). So not a lot of changes so far, but `@electron 7.1.10 => 8.0.0` bump is a major update which might potentially affect the app behavior.

So 4.2.3 fixes the bug so far it seems. (Had to uninstall electronmail-bin (AUR package) to install the binary, might be worth putting a conflict in the pacman binary to not conflict with the aur package (the binary has the package name electron-mail) 

I'm going to restart as i can't see the system tray icon (only issue atm)

**Comment by srappan** [comment] 2020-02-12 18:45
> Can you show the `uname -a` output?
`Linux anarchy 5.5.2-zen2-2-zen #1 ZEN SMP PREEMPT Wed, 05 Feb 2020 22:01:17 +0000 x86_64 GNU/Linux`

**Comment by srappan** [comment] 2020-02-12 18:49
No system tray icon, bit of a wack a mole

**Comment by vladimiry** [comment] 2020-02-12 19:48
> No system tray icon, bit of a wack a mole

Known issue that comes with @electron version 8 upgrade (more exactly comes with [Chromium upgrade](https://github.com/electron/electron/issues/21445#issuecomment-564488600)), see https://github.com/electron/electron/issues/21445 :) I guess you use Xfce. If so install the `xfce4-statusnotifier-plugin` as noted [here](https://github.com/electron/electron/issues/21445#issuecomment-565710027) and then place the respective widget to the Xfce taskbar panel.

Besides that Gnome users will also face some tray icon related issues introduced in @electron version  8, see https://github.com/electron/electron/issues/21576.

I'm considering resetting the `start hidden to tray` state on Linux in 4.2.3  release and will show the respective notification. Since I don't really want Linux users to start 4.2.3  and see no way to activate the app from the tray icon since the icon is missed or flaky. I originally highlighted such intention [here](https://github.com/electron/electron/issues/21445#issuecomment-565061274).

PS I'm preparing a new build for you both to try.

**Comment by vladimiry** [comment] 2020-02-12 21:38
> Linux anarchy

I was not aware of Linux Anarchy project before, fancy stuff :)

**Comment by vladimiry** [comment] 2020-02-12 22:11
The new build assembled from the [issue-250](https://github.com/vladimiry/ElectronMail/tree/issue-250) branch has been uploaded [here](https://mega.nz/#F!J8BTFQrJ!NFz0fm_8DyRXAUWEY6V9Tg). I was not able to reproduce the issue of getting the gray screen but based on my best guess I [disabled the background throttling](https://github.com/vladimiry/ElectronMail/commit/d0c12656f37fb927f030a5325aca834584046dc4#diff-53e676068ed5bfd7c3bef29eac2dd4e3R5) in the @electron. Since currently some of the webview notification messages are timer/interval-based I guessed that disabling the background throttling might help with increasing the app stability because the possible reason of getting a gray screen is absence of the webview notifications (the above-attached log file shows such case).

So can you try the referenced build? I'm going to close the issue if that build works well and move the changes from `issue-250` branch to the `master` one.

**Comment by gourdcaptain** [comment] 2020-02-12 22:27
The build you just linked works without issue on my system once I installed the appindicator plugin you listed. Thanks! :)

**Comment by srappan** [comment] 2020-02-12 23:12
I use i3 and polybar, so still no systray icon, unfortunately

**Comment by vladimiry** [comment] 2020-02-13 04:02
> I use i3 and polybar, so still no systray icon, unfortunately

polybar doesn't seem to support SystemNotifier tray icons. Same as Cinnamon https://github.com/electron/electron/issues/21445#issuecomment-583401526.

**Comment by vladimiry** [comment] 2020-02-13 04:03
> The build you just linked works without issue on my system once I installed the appindicator plugin you listed. Thanks! :)

Closing the issue as resolved. Changes got merged to master branch.

**Closed by vladimiry** 2020-02-13 04:03 UTC

**Comment by vladimiry** [comment] 2020-02-13 04:12
> I use i3 and polybar, so still no systray icon, unfortunately

You might want to consider placing the respective issue in polybar project. Reference there `xfce4-statusnotifier-plugin` and https://github.com/ubuntu/gnome-shell-extension-appindicator projects as an implementation example.

**Comment by vladimiry** [comment] 2020-02-13 12:12
> I use i3 and polybar, so still no systray icon, unfortunately

The [issue](https://github.com/polybar/polybar/issues/2010) got placed just recently.

**Comment by vladimiry** [comment] 2020-02-14 05:48
> Linux anarchy 5.5.2-zen2-2-zen #1 ZEN SMP PREEMPT Wed, 05 Feb 2020 22:01:17 +0000 x86_64 GNU/Linux

@gourdcaptain do you also use 5.5.x kernel?

**Comment by gourdcaptain** [comment] 2020-02-14 05:50
Yep. uname -a result is:
"Linux gsystem 5.5.3-arch1-1 #1 SMP PREEMPT Tue, 11 Feb 2020 15:35:41 +0000 x86_64 GNU/Linux"

**Comment by vladimiry** [comment] 2020-02-14 05:53
@gourdcaptain, thanks. So for now I tend to link the recent app instability issues with using 5.5.x kernel or some recent updates in the Arch repo, see #253. It's a wild guess though.
