### ISSUE TITLE
Sees wrong hard drive or partition

### ISSUE THREAD

**Issue by cjfortu** [vladimiry/ElectronMail#324] opened 2020-09-08 02:31 UTC
OS: Pop!_OS 20.04

I have a dual SSD laptop.  My OS is on one, my home directory is in the other.  It seems that Electronmail does not recognize the location of my home directory.

In the first attached screen shot, the window on the left shows what the browser version of Protonmail sees when I attempt to attach a file, while the window on the right shows what Electronmail sees when I do the same.  On both windows, I went as far back in the directory structure as I could.

In the second are the same windows, but showing what is in the resulting home directory.  On the left is correct, on the right is incorrect.

I'm wondering if there is something I can modify to get Electronmail to read the correct drive or partition.

Thank you.

![Screenshot from 2020-09-07 22-27-23](https://user-images.githubusercontent.com/56611410/92427173-cce27d00-f159-11ea-93af-bb4180e98d28.png)

![Screenshot from 2020-09-07 22-28-21](https://user-images.githubusercontent.com/56611410/92427178-d10e9a80-f159-11ea-85fd-eb80df16a3d8.png)

**Comment by vladimiry** [comment] 2020-09-08 07:45
If you run Flatpak-based package as a security measure only the "downloads" folder is by design exposed to the app. See for details https://github.com/flathub/com.github.vladimiry.ElectronMail/blob/be51b1b327789719efbb690813f7523590d3fabf/com.github.vladimiry.ElectronMail.json#L15

**Comment by vladimiry** [comment] 2020-09-09 16:58
Closing as addressed.

**Closed by vladimiry** 2020-09-09 16:58 UTC
