### ISSUE TITLE
Proton Calendar suddenly not working

### ISSUE THREAD

**Issue by RobertKirchner9** [vladimiry/ElectronMail#459] opened 2021-11-11 00:14 UTC
I use Electron mail to access my Proton account. As of today, when I try to switch out of mail to calendar or settings, it says "oops, something went wrong." I have to log out, quit, restart and log back in again. My calendar is working fine on the web interface.

**Comment by vladimiry** [comment] 2021-11-11 05:43
Duplicate of #457.

**Closed by vladimiry** 2021-11-11 05:43 UTC
