### ISSUE TITLE
Local Store does not download and store all emails

### ISSUE THREAD

**Issue by edwardjohnson11** [vladimiry/ElectronMail#331] opened 2020-09-29 15:42 UTC
I enabled Local Store and waited for it to finish syncing. I noticed it only stored about 10k email when my account in total has over 30k emails (calculated in the "All Mail" view: 50 emails per page, with over 600 of such pages). Is there a way to ensure every single email is downloaded?

ElectronMail v4.8.0
Unofficial ProtonMail Desktop App

Distributed under MIT license.

Electron: 10.0.0-beta.15
Chromium: 85.0.4183.39
Node: 12.16.3
V8: 8.5.210.15-electron.0

Thank you,
Ed.

**Comment by vladimiry** [comment] 2020-09-29 16:53
When you select "All Mail" view in protonmail UI (having not selected any specific email message) then at the right side the UI shows the total emails count. That number should be the same as ElectronMail stores after the syncing process is finished (after the initial sync the app will do only incremental/patch-like/reactive syncing). If those numbers are not the same and the initial/bootstrap sync process got finished then it's an issue.

> 30k emails

The rough estimation for initial/bootstrap sync of such mails count would be 8 hours at least (1k mails syncing roughly takes 15-18 minutes). Even if you have a fast internet the time still will be long since we have to respect the rate-limiting restriction set up API call by protonmail. The time also depends on email size and conversations count/size.

> Is there a way to ensure every single email is downloaded?

The short answer is no since API/server-side things can be changed by proton team at any time without any notice, ie the API is not public. I've never tested the app on such a huge mails count like you reported but it used to work well for me with a few thousand items at least. Also, there were messages before from real users that the app could successfully sync about ~20k emails.

Troubleshooting such kind of issues takes a lot of time and requires extensive communication with issue opener (happened before several times in private mode vie email) and I'm not ready to jump into it right now. But if I will have the issue reproduced on my side then I'd look into it.

**Comment by vladimiry** [comment] 2020-10-20 12:39
A similar issue has been reported by another user: correct initial/bootstrap fetch, but after some days/weeks of using the app the reactive/incremental syncing gets some messages lost (proton ui displays a higher messages count value than is saved in the app's local store).

I've reviewed the syncing code logic but could not yet locate the problem. If someone want's to review the syncing code, the core part of it located [here](https://github.com/vladimiry/ElectronMail/blob/master/src/electron-preload/webview/primary/api/build-db-patch.ts), it would be tough though I think not fully understanding the context and all the use cases.

**Comment by vladimiry** [comment] 2020-10-20 20:11
This is a reactive/incremental sync related message. Did some debugging and realized that:
- Each of two different `https://app.protonmail.ch/api/v4/events/<EventID>`-like requests (with deferent `EventID`) can return the same `response.Messages[ID="some-message-id"] && response.Messages[Action=0]`-like record. This makes me think that either proton's events queue API/backend is somehow buggy since you can't delete the email message twice (`Action=0` represents remove event) and has the respective event put to the events queue or I don't fully understand how this events queue works. Maybe some other action than removing can be served as `Action=0` event, no idea. If the first assumption is correct, ie the API/backend is buggy, then I guess it would explain why some messages get lost during events queue processing.
- I've noticed that `https://app.protonmail.ch/api/v4/events/<ID>` API combines the events rather than serving original individual records. I started iterating the events starting from 20 days old "EventID" value and got fetched only about 30 values until API responded that there are no more new events. Each of that 30 fetched events has a relatively big `response.Messages` array size, like 20+ items (usually bigger). Normally, I do some action with just 2-5 messages at once, not 20+ actions at once, and then I can see in the debugger that individual events with 2-5 updates get processed. Don't know on which criteria they combine the events but maybe they mess some things doing combining.

These are just observations. The issue still can be on my side but doing debugging I found out that `https://app.protonmail.ch/api/v4/events/<EventID>` works not exactly like I originally expected.

**Comment by vladimiry** [comment] 2020-12-08 00:35
Closing this in favor of confirmed #314.

**Closed by vladimiry** 2020-12-08 00:35 UTC
Labels: bug, local store, sync
