### ISSUE TITLE
Unhandled Promise Rejection Failed index emails

### ISSUE THREAD

**Issue by alfredonodo** [vladimiry/ElectronMail#327] opened 2020-09-18 09:11 UTC
Hi,
I'm using the latest version 4.8 of ElectronMail on ubuntu 20.04 64 bit and I get this error:
```
Unhandled Promise Rejection
Error: Failed index emails in 30000ms (mails portions size: 1000)
    at MergeMapSubscriber.project (/opt/ElectronMail/resources/app.asar/app/electron-main.js:1032:327)
    at MergeMapSubscriber._tryNext (/opt/ElectronMail/resources/app.asar/node_modules/rxjs/internal/operators/mergeMap.js:67:27)
    at MergeMapSubscriber._next (/opt/ElectronMail/resources/app.asar/node_modules/rxjs/internal/operators/mergeMap.js:57:18)
    at MergeMapSubscriber.Subscriber.next (/opt/ElectronMail/resources/app.asar/node_modules/rxjs/internal/Subscriber.js:66:18)
    at AsyncAction.dispatch (/opt/ElectronMail/resources/app.asar/node_modules/rxjs/internal/observable/timer.js:31:16)
    at AsyncAction._execute (/opt/ElectronMail/resources/app.asar/node_modules/rxjs/internal/scheduler/AsyncAction.js:71:18)
    at AsyncAction.execute (/opt/ElectronMail/resources/app.asar/node_modules/rxjs/internal/scheduler/AsyncAction.js:59:26)
    at AsyncScheduler.flush (/opt/ElectronMail/resources/app.asar/node_modules/rxjs/internal/scheduler/AsyncScheduler.js:52:32)
```

**Comment by vladimiry** [comment] 2020-09-18 09:17
These are the steps I'd suggest you go through:
- Open the app [settings folder](https://github.com/vladimiry/ElectronMail/blob/master/images/open-settings-folder.jpg).
- Close the app.
- Double the `timeouts.indexingBootstrap` value in `config.json` file (located in the [settings folder](https://github.com/vladimiry/ElectronMail/blob/master/images/open-settings-folder.jpg)).
- Start the app.

**Comment by alfredonodo** [comment] 2020-09-19 08:14
Thank you for the fast reply. I tried with 60000, but I get the same error plus the following:

```
Unhandled Promise Rejection
TypeError: Object has been destroyed
    at BrowserWindow.<anonymous> (/opt/ElectronMail/resources/app.asar/app/electron-main.js:6031:27)
```
    
```
Unhandled Promise Rejection
TypeError: Object has been destroyed
    at Object.toggleBrowserWindow (/opt/ElectronMail/resources/app.asar/app/electron-main.js:1505:36)
    at toggleBrowserWindow (/opt/ElectronMail/resources/app.asar/app/electron-main.js:5166:55)
    at MenuItem.click (electron/js2c/browser_init.js:69:1626)
    at Object.l._executeCommand (electron/js2c/browser_init.js:77:2328)
    at messageBox (electron/js2c/browser_init.js:45:3874)
    at showMessageBoxSync (electron/js2c/browser_init.js:45:4256)
    at handleError (/opt/ElectronMail/resources/app.asar/node_modules/electron-unhandled/index.js:47:24)
    at process.<anonymous> (/opt/ElectronMail/resources/app.asar/node_modules/electron-unhandled/index.js:103:4)
    at processEmit [as emit] (/opt/ElectronMail/resources/app.asar/node_modules/signal-exit/index.js:161:32)
```

**Comment by vladimiry** [comment] 2020-09-19 10:20
`Object has been destroyed` error is not directly related to the original/`Failed index emails in...` error. It's an indication that the browser window instance was destroyed when it was supposed to be live. In your case toggling browser windows via tray icon triggered the issue. Provided log lines don't show the root cause and it's hard to guess what exactly happened. Having the full log file provided with `verbose` log mode enabled could potentially shed more light on the issue (log file in `verbose` mode can be attached here or sent privately to the email specified in the ["author" section of the package.json file](https://github.com/vladimiry/ElectronMail/blob/master/package.json#L5)).

As for the original error. You could keep increasing the `timeouts.indexingBootstrap` value or/and decreasing `indexingBootstrapBufferSize` one (like 1000 => 500). But I think it's not going to help since even 30sec is normally more than enough to index 1000 email messages (of course it depends on computer performance) and because it's something weird happening in your case (that `Object has been destroyed` error is not supposed to happen, I guess might be system/kernel-dependent). Maybe try running the Snap package if you currently running a regular DEB one.

The straightforward errors suppressing/ignoring option would be disabling the `Full-text search` toggle in the "General" app settings. This should prevent the original/`Failed index emails in...` error to happen. And disabling the `Close to tray` toggle should likely suppress the `Object has been destroyed` error. This is of course not a fix but errors suppressing option.

**Comment by vladimiry** [comment] 2020-09-24 12:37
Closing as inactive (log file in verbose mode has not been provider for review).

**Comment by alfredonodo** [comment] 2020-09-25 08:45
Hi,
I'm sorry for the delayed response.
I sent you the log via email.
My system is old, but I think enough powerful in order to run even the inefficient electron framework (i7 37xx, 8 GB RAM DD3, SSD SATA3). I prefer to avoid snap packages. Moreover, with ubuntu 18.04 there were not any problems.

**Comment by vladimiry** [comment] 2020-09-25 10:25
Thank for providing detailed logs. It's now clear that mails indexing process gets broken for you at this place:
```
[error] [preload: database-indexer] [index] dbIndexerNotification.next, action.type: ipc_main_api_db_indexer_notification_actions:Index RangeError: Maximum call stack size exceeded
    at walk (<anonymous>:2652:5)
    at <anonymous>:2665:26
    at Array.forEach (<anonymous>)
    at walk (<anonymous>:2653:9)
    at <anonymous>:2665:26
    at Array.forEach (<anonymous>)
    at walk (<anonymous>:2653:9)
    at <anonymous>:2665:26
    at Array.forEach (<anonymous>)
    at walk (<anonymous>:2653:9)
```

The error occurs in the https://github.com/werk85/node-html-to-text dependency npm-released version of which doesn't support limiting the recursive function calling depth. But such limiting capability seems to be already pushed to repository in https://github.com/werk85/node-html-to-text/pull/172 PR.

So I'm going to replace the dependency npm-url with github-repo-url so I could set the recursion depth limit in ElectronMail code. @alfredonodo, I will ask you then to try a new build. For now just disable the `Full-text search` option on the `General` app options block.

> Moreover, with ubuntu 18.04 there were not any problems.

It's more likely that you recently got a new email message indexing of which triggers the above-listed error (apparently html-based huge/deeply-nested email message). So it's likely about the specific data-source-related error than caused by system upgrade.

> i7 37xx, 8 GB RAM DD3, SSD SATA3

In terms of CPU power, this is a significantly more performant setup than my laptop which doesn't demonstrate any issues in using ElectronMail with default timeouts.

**Comment by alfredonodo** [comment] 2020-09-25 12:48
Hi,
thank you for your detailed and fast analysis. I will try the new build as soon as it will be available.

**Comment by vladimiry** [comment] 2020-09-25 18:07
The work-in-progress build is placed [here](https://mega.nz/folder/g0JHxaSR#Hyih6CMm5Jzp8I9gEwp4qQ). Keep the `verbose` logging mode enabled. If the indexing error still occurs try decreasing the `htmlToText.maxChildNodes` / `htmlToText.maxDepth` values. Besides, in the case of error, you should get the `problematic mail subject: ...` log line printed to log file so you could locate the "problematic" email message (`verbose` log mode).

**Comment by vladimiry** [comment] 2020-09-28 05:51
@alfredonodo thanks for the updated logs. Now the error type is the same, `RangeError: Maximum call stack size exceeded`. But this time it runs off the rails at another place https://github.com/mathiasbynens/he/blob/36afe179392226cf1b6ccdb16ebbb7a5a844d93a/src/he.js#L242 (`he.decode`'s `html.replace` call triggered at https://github.com/werk85/node-html-to-text/blob/7894809a57e9066501b954dbd9c16fd34c3bcebf/lib/formatter.js#L58).

I think I'm going to look for a replacement to `html-to-text` module since it doesn't seem to be well designed for processing large/complex html data. The goal is to replace it with a module that supports streaming processing and doesn't use regexp/recursion techniques heavily so we could safely process large documents (it will likely be slower processing though). I will need then to run some tests to keep the indexing performance acceptable (close to the current level).

**Comment by vladimiry** [comment] 2020-09-28 09:51
Going to get back pure/npm-publshed "html-to-string" module use and then if it fails with RangeError will fallback to iframe-based html to text conversion. So this means simpler code and reliable enough solution.

**Comment by vladimiry** [comment] 2020-09-28 12:07
@alfredonodo, updated build placed [here](https://mega.nz/folder/p8xFQazA#LO5r_JZtV7i5RTSFg5BuTw). I'd recommend removing/renaming the existing log file before starting this build.

**Comment by vladimiry** [comment] 2020-09-30 21:22
There were no more new reports since the recent build was shared (see previous message), so closing as resolved.

**Closed by vladimiry** 2020-09-30 21:22 UTC
Labels: local store

**Comment by alfredonodo** [comment] 2020-10-01 15:46
Hi,
have you received my last log?

**Comment by vladimiry** [comment] 2020-10-01 20:42
>  have you received my last log?

The latest log I've received dated Sep 27th. The latest build shared in https://github.com/vladimiry/ElectronMail/issues/327#issuecomment-699965878 is assembled and shared after reviewing that log and applying the following change:

> Going to get back pure/npm-publshed "html-to-string" module use and then if it fails with RangeError will fallback to iframe-based html to text conversion. So this means simpler code and reliable enough solution.

**Comment by alfredonodo** [comment] 2020-10-02 13:58
Ok even the last message of Sep 28th related to the error is addressed?

**Comment by vladimiry** [comment] 2020-10-02 15:59
Yes. But I'm open to reviewing an updated log file. That's why I asked you to start a new build with a clean/new log file.

**Comment by KillyMXI** [comment] 2020-10-23 15:47
@vladimiry thanks for linking to that node-html-to-text PR. It was interesting to look at some real word scenario where people consider using html-to-text and at the issues associated with it.

Am I right that this issue happened at the attempt to convert very large emails? Probably from some mailing list, with a crazy amount of original messages carried along? I wonder if there are public examples available to reproduce it for testing.

That's is right that html-to-text was made with the goal to get a human-readable text rather than high throughput. All this formatting effort doesn't seem relevant for search index building purposes.

I will keep this in mind for future refactorings. For now it is possible to gain some performance boost by disabling word wrapping. Maybe making everything to be considered as preformatted text. If we take this idea of stripping down for performance boost to extreme - we will be left with dumping htmlparser2 output to a string. Maybe that's more suitable for indexing. Maybe htmlparser2 will be next to fail on big input.

**Comment by vladimiry** [comment] 2020-10-23 18:09
@KillyMXI, the html-to-text module normally does the job well but yes on some data sets it fails with "RangeError: Maximum call stack size exceeded"-like error which is expected since recursion technique is used there internally. I think a regular way to avoid recursion is to keep pushing the iteration-related data to the array and processing the array in a "while loop until the array is not empty" (the execution stack won't be used heavily and so there won't be RangeError thrown).

Regarding data example. There is not a lot publicly available data samples I have but I remember the module was not able to process [this](https://lists.sr.ht/~sircmpwn/public-inbox/%3C20190405183406.4434-1-archaeme%40biribiri.dev%3E/raw) data (picked through the "Download raw message" link from [this](https://lists.sr.ht/~sircmpwn/public-inbox/%3C20190405183406.4434-1-archaeme%40biribiri.dev%3E) page).

**Comment by KillyMXI** [comment] 2020-10-23 19:56
Yeah. There are a couple of approaches I have in mind. One will be a while loop with a home-grown stackfor a backwards path (based on a linked list, similar to what I use in the upcoming version for different purposes) . And the other will be to replace htmlparser2 and do the processing on the go, without accumulating much data. I feel like htmlparser2  is a limiting factor for multiple reasons and this is one more. Although latter is much more involving obviously.

On the example: wow. Looks like a fuzz test, with a lot of garbage and unescaped angle brackets. And it's a raw text that doesn't seem to really need further processing in the first place.
Html-to-text expects html input, htmlparser2 parses whatever input without complaining... It is definitely something to keep in mind, but I'm not sure it (1) can be and (2) should be supported. If it won't crash - it can produce garbage output.
It is related to https://github.com/werk85/node-html-to-text/issues/202
If there is a way to discern raw text from html emails - that would solve the issue in the most efficient way possible - by not doing unneeded job.

**Comment by vladimiry** [comment] 2020-10-23 23:39
Yes, maybe one day I will come to the point of distinguishing the text and html content. I think proton checks the body type based on mime type and If I have this value saved locally then that should be easy to utilize. So far the sandboxed-iframe/DOM-based text resolving fallback takes place if html-to-text throws RangeError. Totally agree that's a crazy data input but still in reality such case is technically possible to happen.

**Comment by vladimiry** [comment] 2020-10-24 13:21
> If there is a way to discern raw text from html emails - that would solve the issue in the most efficient way possible - by not doing unneeded job.

> Yes, maybe one day I will come to the point of distinguishing the text and html content. I think proton in its web apps checks the body type based on mime type and If I have this value saved locally then that should be easy to utilize. So far the sandboxed-iframe/DOM-based text resolving fallback takes place if html-to-text throws RangeError.

[Here](https://github.com/vladimiry/ElectronMail/commit/59411958bcdab3c44932d2fcb116e881cd64e609#diff-87ea5ee95bb8224ef55a5a339c2751669ec526b15d1fe142a6a04f9999cf76a3R111-R113) it is.
