### ISSUE TITLE
Unable to see names when opening dialog to add attachment

### ISSUE THREAD

**Issue by ajay-actuary** [vladimiry/ElectronMail#399] opened 2021-05-09 07:27 UTC
I installed electron mail from snap stores to use with Protonmail. I use Arch Linux + Gnome 40 + Nautilus file manager. 

When I open the attachment dialog, I get a dialog that looks like this with no English names:
https://ibb.co/CnNt6hc

Is this a font dependency issue?

Thanks.

**Comment by vladimiry** [comment] 2021-05-09 07:30
Closing as duplicate of #391 (unresolved).

**Closed by vladimiry** 2021-05-09 07:30 UTC
