### ISSUE TITLE
[Question] Some kind of new mail notification cross-platform

### ISSUE THREAD

**Issue by 0xacdc** [vladimiry/ElectronMail#422] opened 2021-07-19 15:56 UTC
What I mean: 
Right now, on macOS I see a Notification like "Protonmail[x] has received a new mail" for every new mail.

- If there will be a title for every added account, it will be more readable like "Shopping account has new mails"
- If this app will have an option to specify for example a shell script, and execute it with the message from first option as argument, there will appear a possibility to send this arguments where you want, to other email or chat.

**Comment by vladimiry** [comment] 2021-07-19 16:06
> If there will be a title for every added account, it will be more readable like "Shopping account has new mails"

The app by design shows only the account index in the desktop notification (privacy matter). But you can set any "Login alias" value in the "Advanced options" block located on the account edit form and it then will be displayed instead on the index.

> If this app will have an option to specify for example a shell script, and execute it with the message from first option as argument, there will appear a possibility to send this arguments where you want, to other email or chat.

Noted.

**Comment by ELLIOTTCABLE** [comment] 2021-09-07 23:08
I'd also like the ability to opt-out of the privacy-preserving "hiding" behaviour — many apps offer a toggle-setting for that (at least on iOS; I can't speak as much for desktop-macOS apps!)

**Comment by vladimiry** [comment] 2021-09-07 23:29
> opt-out of the privacy-preserving "hiding" behaviour

> set any "Login alias" value...

**Comment by ELLIOTTCABLE** [comment] 2021-09-13 16:34
That doesn't seem to opt-out of the hiding behaviour? That just changes the title *above* the still-hidden message.

**Comment by vladimiry** [comment] 2021-09-13 16:44
Correct. It only changes the title. Showing the message content is "wontfix" for now.

**Comment by tukusejssirs** [comment] 2022-02-19 13:25
What about having an option to include the email sender and subject? I run ElectronMail  on my computers only, therefore I don’t want to open ElecronMail to check from whom I got a new email. If I do something where a new email notification might be disturbing (e.g. recording/sharing the screen), I’ll simpl turn on the Do Not Dirtub.

**Comment by vladimiry** [comment] 2022-03-26 12:12
Closing as duplicate of #387.

**Closed by vladimiry** 2022-03-26 12:12 UTC
Labels: enhancement, privacy
