### ISSUE TITLE
Lost focus in composition window and non functional cmd-x in 4.2.1 for macOS

### ISSUE THREAD

**Issue by ylluminate** [vladimiry/ElectronMail#248] opened 2020-02-02 15:42 UTC
Something I've noticed while using 4.2.1 in macOS is that while composing a message focus frequently and randomly leaves the composition area. The focus still remains on the ElectronMail.app, but it simply does not stay in the small writing window. 

Further, I've found that command-x does not cut text therefrom either. Command-c seems to copy and command-v pastes fine, but cmd-x is broken.

**Comment by vladimiry** [comment] 2020-02-02 16:14
Can confirm the issue.

**Comment by vladimiry** [comment] 2020-02-02 17:51
@ylluminate, can you confirm the focus loosing issue resolved in [this](https://mega.nz/#F!1sYxSShI!Dj7M-FdDcDVx0lQvepi08A) build? I'm going to publish a new release when the lost focus issue gets confirmed as resolved.

**Comment by ylluminate** [comment] 2020-02-02 19:17
@vladimiry yes, the focus issue is resolved now, but you're right - cmd-x is still broken.

**Comment by vladimiry** [comment] 2020-02-02 19:28
>  cmd-x is still broken.

This is why the issue will remain open. But it looks like the app never had custom code for cmd+x working on macOS as it has for cmd+v/cmd+c (I thought it did):
https://github.com/vladimiry/ElectronMail/blob/2cce6f0c04d8eed08be6c9c7a82fe17257b00328/src/electron-preload/lib/events-handling/handle-keydown.ts#L61-L67
and
https://github.com/vladimiry/ElectronMail/blob/2cce6f0c04d8eed08be6c9c7a82fe17257b00328/src/electron-main/api/endpoints-builders/general.ts#L147-L159
and
https://github.com/vladimiry/ElectronMail/blob/2cce6f0c04d8eed08be6c9c7a82fe17257b00328/src/shared/api/main.ts#L121

So I guess I just need to add cmd+x into this list. So new build is coming :) If no success then then current master branch will be published as 4.2.2.

**Comment by vladimiry** [comment] 2020-02-02 21:23
> cmd-x is still broken.

What about [this](https://mega.nz/#F!soQDlCiQ!PmKaB7dGFGug29blnnXl7Q) build?

**Comment by ylluminate** [comment] 2020-02-02 21:51
Wow, well it DID cut this time!  BUT it also crashed instantly following cmd-x:
https://p153.p0.n0.cdn.getcloudapp.com/items/X6uDw414/Process+++++++++++++++Electron.txt

**Comment by vladimiry** [comment] 2020-02-03 03:44
Thanks for attaching the log but unfortunately at this time I won't be able to post a new crush-like bug in https://github.com/electron/electron/issues/ since I don't have a macOS system at hand needed to prepare a minimal reproducible isolated repository based on https://github.com/electron/electron-quick-start.

> Wow, well it DID cut this time! BUT it also crashed instantly following cmd-x:

What I did there is simply extended the workaround for not working on macOS cmd-c/cmd-v commands applied as #67 resolution more than a year ago. The workaround still required sine the respective Electron/upstream issue still not fixed.

The [vscode](https://github.com/microsoft/vscode) by the way also suffers from the same issue. What they decided to do is to replace webview use with a regular iframe. Moving to regular iframes would be big task in the case of ElectronMail so such refactoring is not considered for now.

So will be publishing soon a new release with lost focus issue fixed but not working cut hotkey remains unresolved.

**Comment by vladimiry** [comment] 2020-02-03 05:27
Lost focus fix released in https://github.com/vladimiry/ElectronMail/releases/tag/v4.2.2.

**Comment by vladimiry** [comment] 2020-02-13 05:07
Closing this issue as lost focus problem got fixed. Cmd+x issue moved in #251.

**Closed by vladimiry** 2020-02-13 05:07 UTC
Labels: bug, upstream
