### ISSUE TITLE
Can't download attachments on windows

### ISSUE THREAD

**Issue by Th3Tr00p3r** [vladimiry/ElectronMail#339] opened 2020-10-20 08:26 UTC
OS: windows 10.1.19041
ElectronMail v4.8.0

Hi,
I can't seem to download attachments.
the file-saving dialog comes up, but when I press save nothing happens (expecting to see file in the saving directory)
Any ideas?

Thanks,
Ido

**Comment by vladimiry** [comment] 2020-10-20 08:59
Is it proton's export or the one implemented in ElectronMail (described in [v4.7.0](https://github.com/vladimiry/ElectronMail/releases/tag/v4.7.0))?

**Comment by Th3Tr00p3r** [comment] 2020-10-20 09:03
sorry, i didn't understand you...
I'm using ElectronMail, viewing an email in the 'online' mode, and pressing on an attachment to download (not exporting)

**Comment by vladimiry** [comment] 2020-10-20 09:06
It's clear now, thanks for clarification.

**Comment by vladimiry** [comment] 2020-10-20 09:22
I tend to think that this is an upstream issue.

Does attachments downloading work for the same email message if you do that in browser? Please don't open https://beta.protonmail.com in browser but https://mail.protonmail.com/ (production version) since:
- Currently deployed on https://beta.protonmail.com web mail client is not the same the v4.8.0 comes with (they significantly updated it since v4.8.0 app version got released).
- I have a reason to believe that currently deployed on https://beta.protonmail.com web mail client has a flaw that leads to privacy-compromising (the issue has been reported).

PS I just successfully exported 0.173MB + 9.3MB attachments from the email message using v4.8.0 app build. Exporting the 9.3MB file took some time after the destination folder selection dialog got closed but it succeed.

**Comment by Th3Tr00p3r** [comment] 2020-10-20 09:53
The same attachment downloads normally from [](https://mail.protonmail.com/inbox).

**Comment by vladimiry** [comment] 2020-10-20 10:06
Ok, we can't easily verify in browser the same proton's web mail client that's packaged into the v4.8.0 app release since this version is not deployed anywhere. Same as we should not use live https://beta.protonmail.com which I currently have packaged into the v4.9.0 (see why in my previous message). So the only way to get the issue fixed for you in the app is to wait until I release v4.9.0 which is currently blocked by reported but not yet confirmed/solved upstream issue. @Th3Tr00p3r I'm going to ask you to try v4.9.0 build when I think it's ready for testing.

Export works for me in v4.8.0 but I'm ok marking the issue as a bug since it doesn't work for you.

**Comment by Th3Tr00p3r** [comment] 2020-10-20 10:09
OK, thanks - I'll notify if anything changes somehow.
I initially began using ElectronMail for backing up my emails, but it'd be great if I could use it exclusively.

**Comment by vladimiry** [comment] 2020-10-20 10:26
> I initially began using ElectronMail for backing up my emails

See the attachments export feature enabled in [v4.7.0](https://github.com/vladimiry/ElectronMail/releases/tag/v4.7.0). This feature is meant to be used for backup (manual per-email export is a headache). Notice that on the full-text search form you get the "data after" filter value which can be used for incremental backup. Like you backup all the stuff on 9th March. Then next time you selected the date value "after 9th March" and export only not yet exported stuff. It's helpful for "export with attachments" case so you don't download all the attachments from internet each time you backup the mails. Also the "Attachments" toggle can be used here to filter only the messages that have attachments.

![123](https://user-images.githubusercontent.com/1560781/96573770-459b3400-12d7-11eb-82f4-757bd3f6ca73.png)

**Comment by Th3Tr00p3r** [comment] 2020-10-20 10:39
Yeah I've already taken advantage of that, I'm just saying I'd like to be able to casually download attachments in the 'online' mode, then nothing would stop me from ditching the browser interface and use only ElectronMail

**Comment by vladimiry** [comment] 2020-10-20 10:43
> Yeah I've already taken advantage of that,

Does it work by the way for the same email message it doesn't work for in "Proton UI"?

**Comment by Th3Tr00p3r** [comment] 2020-10-20 10:54
I tried now to export (including attachments) an email containing an attachment which I can't download 'online', and was able to open it from the exported email

**Comment by Th3Tr00p3r** [comment] 2020-10-20 10:54
so it's an issue only with the 'online' UI

**Comment by vladimiry** [comment] 2020-10-20 10:56
Thant for testing that case. So yes it looks like an upstream issue.

**Comment by vladimiry** [comment] 2020-11-05 12:27
Closing as an upstream issue.

**Closed by vladimiry** 2020-11-05 12:27 UTC
Labels: bug, upstream, workaround-exists

**Comment by Th3Tr00p3r** [comment] 2020-11-10 08:54
Update: I now believe this isn't an upstream issue, but an issue somewhere in my windows definitions. I am able to save in D: drive but not in C: - same thing happens for my Signal desktop. I'll figure out how to fix it but it seems completely unrelated to ElectronMail.
Sorry for the trouble!

**Comment by vladimiry** [comment] 2020-11-10 09:16
Nice. Thanks for the update.
