### ISSUE TITLE
Recently started to do this.

### ISSUE THREAD

**Issue by daphniamantis** [vladimiry/ElectronMail#270] opened 2020-03-13 17:17 UTC
Unhandled Error
TypeError [ERR_INVALID_URL]: Invalid URL: null
    at resolveRequestProxy (C:/Program Files/ElectronMail/resources/app.asar/app/electron-main.js:7327:13)
    at Function.<anonymous> (C:/Program Files/ElectronMail/resources/app.asar/app/electron-main.js:7292:30)

**Comment by vladimiry** [comment] 2020-03-13 17:56
- System version?
- App version?
- When did it start to happen?
- It started to happen right after you switched to the new version or you were using some version for a while and then it started to happen just like out of the blue?
- Does it still happen if you rollback to previous app version?

Brief code review says to me that `origin` header fo the XHR request for unknown yet reason gets set to `null` for you.

**Comment by daphniamantis** [comment] 2020-03-13 21:19
Windows 10 Enterprise (Ryzen 3950x)
Latest version 4.4.1
It started last night happened 2 times, no program restart worked, no whole pc restart worked, just reinstall app
It started with the new version (I always update to the latest as soon as I receive the update email)
I reinstalled the new version and it is better now. I haven't tried older versions as they had a huge flaw (I have a mouse with side back and forth buttons and every time I used back it just exit from the app, no earlier versions did that and I like to get back to main screen with them after reading an email). This version is good again from this back and forth button point of view.

I can code some front end stuff no back end yet.

You are at a GOD level and this program is awesome, thank you for your work. You are a great example for my future coding studies. It would be great if you would create an Udemy course. 
I want to learn to code at this level, it must be a perfect life. Keep up the good work.

Thank you, 
Andrew

**Comment by vladimiry** [comment] 2020-03-14 08:15
So far I tend to think that issue being caused by `@electron, 8.0.1 => 9.0.0-beta.5 (c85062c)` update since the involved code was not recently changed. This is why I asked you to try previous @electron v8 based version, v4.4.0.

**Comment by daphniamantis** [comment] 2020-03-14 13:13
@electron, 8.0.1 => 9.0.0-beta.5 (c85062c) resistance is futile. You will be assimilated.

It works now. If won't I'll go back to earlier version. Thank you. You are great! You've made my day. 
We would get on well in person. 😊

**Comment by vladimiry** [comment] 2020-03-14 13:26
I will close the issue for now. I like resolving the issues not changing any code :)

**Closed by vladimiry** 2020-03-14 13:26 UTC
