### ISSUE TITLE
Unsigned Calendar

### ISSUE THREAD

**Issue by emobortnik** [vladimiry/ElectronMail#705] opened 2024-10-27 15:00 UTC
Unhandled Promise Rejection
Error: Failed to resolve file system resource directory from the "webclient://calendar.proton.me/mail" request
    at resolveFileSystemResourceLocation (/app/ElectronMail/resources/app.asar/app/electron-main/index.cjs:76421:57)
    at AsyncFunction.<anonymous> (/app/ElectronMail/resources/app.asar/app/electron-main/index.cjs:76455:42)

**Comment by vladimiry** [comment] 2024-10-27 15:02
Did you open Calender via the respective icon on the right side panel?

**Comment by babebort** [comment] 2024-10-27 15:03
![image](https://github.com/user-attachments/assets/258b58d0-1334-48f9-a707-2371aa372563)

**Comment by babebort** [comment] 2024-10-27 15:04
> Did you open Calender via the respective icon on the right side panel? If not, what was the trigger action for the issue?

I didnt open it , just after sign-in get red notify in app and then this error

**Comment by babebort** [comment] 2024-10-27 15:13
I don't know how to correctly reproduce it but after restart its the same error and the calendar is not working.


```
Unhandled Promise Rejection
Error: Failed to resolve file system resource directory from the "webclient://calendar.proton.me/mail" request
    at resolveFileSystemResourceLocation (/app/ElectronMail/resources/app.asar/app/electron-main/index.cjs:76421:57)
    at AsyncFunction.<anonymous> (/app/ElectronMail/resources/app.asar/app/electron-main/index.cjs:76455:42)
```

**Comment by vladimiry** [comment] 2024-10-27 15:18
Is the "desktop notifications for calendar events" toggle enabled in the settings? If so, try disabling it. This feature/option is experimental, and I don't normally pay attention to it when preparing a new release, as this feature going to be dropped.

![desktop notifications for calendar events](https://github.com/user-attachments/assets/215c810a-1181-4947-95d1-aa62c45db215)

> I don't know how to correctly reproduce it but after restart its the same error and the calendar is not working.

Normally, when the "desktop notifications for calendar events" toggle disabled (default state), the app should not even try loading Calendar without explicit user command to do so (apps menu click). So there is still something hidden from me.

**Comment by babebort** [comment] 2024-10-27 15:26
![image](https://github.com/user-attachments/assets/5b9b98f6-af33-4443-a06c-82c99f93b990)

After toggled off its this the same issue even after restart app

```
Unhandled Promise Rejection
Error: Failed to resolve file system resource directory from the "webclient://calendar.proton.me/mail" request
    at resolveFileSystemResourceLocation (/app/ElectronMail/resources/app.asar/app/electron-main/index.cjs:76421:57)
    at AsyncFunction.<anonymous> (/app/ElectronMail/resources/app.asar/app/electron-main/index.cjs:76455:42)
```

**Comment by vladimiry** [comment] 2024-10-27 15:30
The toggle is ON at the screenshot.

The assumption is that when the toggle disabled, the app should not do background Calendar loading for the desktop notifications purpose.

Btw, consider trying the work-in-progress build shared in https://github.com/vladimiry/ElectronMail/issues/694#issuecomment-2400871180.

**Comment by babebort** [comment] 2024-10-27 15:37
![image](https://github.com/user-attachments/assets/59b29b6e-f0e3-4f4e-b90c-4cb4a96be09f)
just sent you a malformed screenshot

**Comment by vladimiry** [comment] 2024-10-27 15:42
Thanks for the update. Unfortunately, I have no more workaround ideas for the issue at this time as I can't image other workflows, when the Calendar would start loading itself automatically.

**Comment by babebort** [comment] 2024-10-27 15:55
From that [build](https://mega.nz/folder/91wkXRiR#1mMuRf8HS0iFAg2Cj8c01w) I downloaded  "electron-mail-5.2.4-linux-amd64.snap"  and after sudo snap install electron-mail-5.2.4-linux-amd64.snap got error: cannot find signatures with metadata for snap "electron-mail-5.2.4-linux-amd64.snap"


Btw, should I delete stable build before installing that one?

**Comment by vladimiry** [comment] 2024-10-27 16:00
> Btw, should I delete stable build before installing that one? Or it would be installed two different version ?

I didn't try this scenario, but the guess is that 2 versions will be installed.

When executing `snap install electron-mail-5.2.4-linux-amd64.snap` try adding `--dangerous` option to it or there are other Linux package types other than Snap.

**Comment by babebort** [comment] 2024-10-27 16:04
But without sudo is the same issue

or what did u mean?

**Comment by babebort** [comment] 2024-10-28 17:08
Still no idea? I love your app but i critically need calendar for work)

**Comment by vladimiry** [comment] 2024-10-28 17:15
>  i critically need calendar for work)

Did you actually try opening the Calendar app?

![calendar](https://github.com/user-attachments/assets/1c1ac63e-eefd-4951-80da-a78592c4013e)

If I'm correct, you only posted screenshots of the Mail/Inbox app so far, so I thought the issue is only a weird error, but the Calendar app itself as a thing is ok.

**Comment by babebort** [comment] 2024-10-28 17:24
![image](https://github.com/user-attachments/assets/6c81d5b7-1df5-40a4-924b-46a2bf98463a)
![image](https://github.com/user-attachments/assets/7e4f3a44-e235-4efb-a584-6ebb30f1f4e2)



in official app its not wokring, 

right, its loading more than usual in [PWA](https://help.vivaldi.com/desktop/miscellaneous/progressive-web-apps/)

this pc has a low performance btw, could it be a reason?

**Comment by vladimiry** [comment] 2024-10-28 17:33
> this pc has a low performance btw, could it be a reason?

Technically, if they didn't test it on a low performance hardware and low speed network, then a [race of issues](https://en.wikipedia.org/wiki/Race_condition) might exist there. But I know nothing about official app, have never tried it and didn't get familiar with the implementation details. The guess is that they don't pack the web client into the app as a static resource, as done in here ElectronMail.

So, did I get it right that you got the Calendar working in the app?

**Comment by vladimiry** [comment] 2024-10-28 17:36
No, I mean, when you do this https://github.com/vladimiry/ElectronMail/issues/705#issuecomment-2442175668 using ElectronMail?

**Comment by babebort** [comment] 2024-10-28 17:46
it works when i open it  from there

**Comment by vladimiry** [comment] 2024-10-28 17:49
> it works when i open it from there

That is a way to open it in ElectronMail.

So I was correct:

> I thought the issue is only a weird error, but the Calendar app itself as a thing is ok.

Adding a glitch "label" to the issue.

**Comment by babebort** [comment] 2024-10-28 17:50
![image](https://github.com/user-attachments/assets/9a7bd5b9-74c2-4275-bbd3-ee80bda6ae29)

itself it's working but when embed - doesn't work

**Comment by vladimiry** [comment] 2024-10-28 17:54
> itself it's working but when embed - doesn't work

Is it the only issue? I initially asked a clarifying question in https://github.com/vladimiry/ElectronMail/issues/705#issuecomment-2440057971 to narrow down the issue scope and got the impression that it's something else.  The embedded Calendar is not supposed to work in ElectronMail, details available in the pinned #579.

**Comment by babebort** [comment] 2024-10-28 17:59
> Did you open Calender via the respective icon on the right side panel? If not, what was the trigger action for the issue?

this error sometimes appears when I first sign-in, when the calendar opens by itself, but also when I press  that button  right side pane

![image](https://github.com/user-attachments/assets/6e2570c0-f55c-4772-bb3d-50488ca9d518)

**Comment by vladimiry** [comment] 2024-10-28 18:01
> this error sometimes appears when I first sign-in, when the calendar opens by itself

I'm not familiar with the scenario of how to trigger this action (not a Calendar user). But the issue itself is a duplicate of #579, so closing it.

**Closed** 2024-10-28 18:02 UTC
Labels: glitch, distr: snap

**Comment by vladimiry** [comment] 2024-10-28 22:08
> this error sometimes appears when I first sign-in, when the calendar opens by itself

Btw, the embedded calendar, and the respective button too, supposed to be removed in the above-shared build, https://github.com/vladimiry/ElectronMail/issues/694#issuecomment-2400871180 I didn't test it though yet, so maybe you will since the `when the calendar opens by itself` behavior might be annoying, if you use the app.
