### ISSUE TITLE
Spell checking broken in macOS

### ISSUE THREAD

**Issue by ylluminate** [vladimiry/ElectronMail#431] opened 2021-09-04 19:45 UTC
It appears that spell checking no longer works in macOS releases.

**Comment by vladimiry** [comment] 2021-09-04 19:50
I won't be able to look into the issue anytime soon as I don't get along with the macOS system.

**Comment by ylluminate** [comment] 2021-09-04 19:52
Can I help in some fashion? OpenCore is doing great as well for a lot of people in helping systems to work well. For example, my old MacPro systems from 2009 to 2010 are working great with OpenCore Legacy Patcher running Big Sur+.

**Comment by vladimiry** [comment] 2021-09-04 20:01
> It appears that spell checking no longer works in macOS releases.

How exactly does the problem manifest itself?
Does the spellchecking menu get displayed when you click the right mouse button on the input control?
You got the spellchecking context menu but no languages in it to select?
You got the spellchecking context menu but no correction options listed to pick one?

**Comment by ELLIOTTCABLE** [comment] 2021-09-07 23:04
At least under minimal testing, this seems to work fine for me:

<img width="642" alt="Screen Shot 2021-09-07 at 18 02 46" src="https://user-images.githubusercontent.com/200/132421160-939a2377-565a-432c-9eea-33115eccb950.png">

I had to do something unusual-for-macOS, that I assume is an Electron limitation — I had to right-click the text-area and select "Check Spelling" to enable the feature; but after that, it seems passable.

**Comment by vladimiry** [comment] 2021-09-07 23:16
Thanks @ELLIOTTCABLE for the input, adding the "glitch" label then.

> I had to do something unusual-for-macOS

This is probably because of this menu, and overall the app's spellcheck feature UX was designed and implemented in a custom way. The feature in the app required relatively significant work to be done since at that time @electron didn't have the complete build-in spellcheck implementation. Now @electron has it as a given by @chromium thing but I still tend to think that it's not being very well maintained in @electron (I've observed a list of related issues and some of them a still unresolved), so I don't switch to app to it yet (maybe when I switch the UX will be looking more general).

> I had to right-click the text-area and select "Check Spelling" to enable the feature

Makes sense I think since the feature is designed to be opt-in partially because the native module/dependency gets involved here and such modules sometimes cause naughty issues, like severe crashes, so I better keep them disabled by default and load lazily/by-demand (when the feature is enabled).

**Comment by vladimiry** [comment] 2022-02-20 15:06
Closing as invalid issue.

**Closed by vladimiry** 2022-02-20 15:06 UTC
Labels: need-more-info, glitch, upstream, env-dependent
