### ISSUE TITLE
Human verification: To fight spam and abuse, please verify you are human.

### ISSUE THREAD

**Issue by ltraveler** [vladimiry/ElectronMail#423] opened 2021-07-19 16:02 UTC
I can´t log in to my account. There is no captcha or any other method to pass a human verification system. The client just waiting for an unknown event/state.
![image](https://user-images.githubusercontent.com/5625337/126190910-4c89ed61-9419-4b13-8943-489406aeb68e.png)

**Comment by vladimiry** [comment] 2021-07-19 16:04
Duplicate of #419.

**Closed by vladimiry** 2021-07-19 16:04 UTC
