### ISSUE TITLE
Failed to load webclient due to time-out

### ISSUE THREAD

**Issue by joshirio** [vladimiry/ElectronMail#247] opened 2020-02-02 13:20 UTC
![t7cxVxd6Kk](https://user-images.githubusercontent.com/12795018/73608697-66472080-45c6-11ea-8920-70d7870845aa.png)

This message appears almost every time I start ElectronMail on cold start. If I releaunch the app it works fine. The issue is that the machine I experience this is a fan less, low power[ mini pc](https://www.asus.com/us/Mini-PCs/Mini-PC-PN40/) so I guess it times out before the client is loaded, then it doesn't help that I have 3 accounts to load at start-up.

Would you consider increasing the time-out? Or is there already a config that can be changed manually?

**Comment by vladimiry** [comment] 2020-02-02 13:43
Does the v4.0.0 work without errors on the same hardware?

This specific timeout is currently hard-coded and was introduced with the added in v4.2.0 `persistent session` feature. I'm going to make this timeout configurable and probably increase the default value.

> it doesn't help that I have 3 accounts to load at start-up

Maybe for now try setting up auto-login delay for the 2nd and 3rd accounts, so accounts get loaded in sequence rather than in parallel. If you will be setting up delays consider using [this](https://mega.nz/#F!I5QUQSjT!DkaNayF01CcrX4GBSr8j_w) build as it gets back delaying functionality after the explicit logout.

**Comment by joshirio** [comment] 2020-02-02 14:22
Thanks I'll try, yes I'm using the lastest version.

**Comment by joshirio** [comment] 2020-02-02 14:57
![eFaHMDcNh2](https://user-images.githubusercontent.com/12795018/73610124-69e1a400-45d4-11ea-8941-5ae7ed7cffaf.png)

Installed 4.0.0 and now my accounts are gone, the message was schon that a tutanota account was removed but I didn't have any tutanota accounts added...

Now I have the following files, including a tutanota backup:
![CxHgeN4ski](https://user-images.githubusercontent.com/12795018/73610143-a1505080-45d4-11ea-8705-aebdac3d893a.png)

Is there a way to restore the settings from that backup or do I have to reconfigure it?
Thanks

**Comment by vladimiry** [comment] 2020-02-02 15:20
The issue of accounts settings lost with reverting back to 4.0.0 cause by [comparing accounts](https://github.com/vladimiry/ElectronMail/blob/v4.0.0/src/electron-main/storage-upgrade.ts#L285) using `type` property which got removed in 4.0.0+ releases (49acf0ead558f0356378397921304747eff8c01f). In never versions that comparison [got improved](https://github.com/vladimiry/ElectronMail/blob/fb4fef50423e67fe06562f1f448c0c761c515d2f/src/electron-main/storage-upgrade.ts#L305-L306).

In general, I forgot to mention that the app only supports backward compatibility so it picks up "old" settings and converts them if needed but not the other way around, my bad.

That file, `settings.bin.tutanota-...` is a backup which compatible with 4.2.1. So you could renaming it back to settings.bin and keep using 4.2.1.

**Comment by joshirio** [comment] 2020-02-02 15:42
Ok thanks, BTW 4.2.2 (your custom build linked above) works good with auto delay, so that would be an acceptable work around for me, if you don't decide to increase the time-out.

**Comment by vladimiry** [comment] 2020-02-02 15:48
> if you don't decide to increase the time-out.

I've just trigger the build on CI env with the configurable timeout change included. So if build process goes well you will get that timeout to be configurable in about an hour.

> BTW 4.2.2 (your custom build linked above) works good with auto delay, so that would be an acceptable work around for me

It makes sense since without delays the CPU gets utilized more intensively due to the parallel webview processes creating and blank.html loading. Thanks for confirming that adding delays stuff helped to avoid the timeout error.

**Comment by vladimiry** [comment] 2020-02-02 15:50
> your custom build linked above

Not really custom but more like nightly as it was assembled from the master branch.

**Comment by vladimiry** [comment] 2020-02-02 16:31
> So if build process goes well you will get that timeout to be configurable in about an hour.

I will be triggering a new build with lost focus fixed. That is a quite annoying bug so new app release is going to be published soon.

**Comment by vladimiry** [comment] 2020-02-02 17:53
@joshirio, [this](https://mega.nz/#F!1sYxSShI!Dj7M-FdDcDVx0lQvepi08A) build comes with the configurable blank.html page loading timeout and the default value increased 2sec=>15sec. Going to publish it as v4.2.2 release when #248 confirmed as resolved.

**Comment by joshirio** [comment] 2020-02-02 19:06
yes works very well, no more errors, thank you!

**Comment by vladimiry** [comment] 2020-02-03 05:26
Released in https://github.com/vladimiry/ElectronMail/releases/tag/v4.2.2.

**Closed by vladimiry** 2020-02-03 05:26 UTC
