### ISSUE TITLE
Error : A javascript error occurred in the main process - Windows 10

### ISSUE THREAD

**Issue by MoDzCatZ** [vladimiry/ElectronMail#294] opened 2020-05-19 16:05 UTC
I just downloaded your application for windows.
It installs without problem, but once I want to launch it (and those even with administrator rights) 

![Screenshot_1](https://user-images.githubusercontent.com/2751766/82350070-2b44ed80-99fb-11ea-9fcb-f27d08283992.png)

In folder roaming : 
![Screenshot_2](https://user-images.githubusercontent.com/2751766/82350116-3a2ba000-99fb-11ea-94f4-556e1f0a53d7.png)

Thank you resolved my problem

**Comment by vladimiry** [comment] 2020-05-19 20:21
The app only has app-level logs. The custom app code didn't get started in your case so there won't be useful logging information (your seconds screenshot demonstrates that).

https://github.com/vladimiry/ElectronMail/releases/download/v4.4.2/electron-mail-4.4.2-windows-nsis-installer.exe installed comes with `sodium.node` file in it (you can unpack it by running `7za x electron-mail-4.4.2-windows-nsis-installer.exe` and locate `./resources/app.asar.unpacked/node_modules/sodium-native/build/Release/sodium.node` file there). So the issue is specific to your system. For some reason that file didn't come to right place, maybe antivirus software or other blockers got it nuked, no clear idea.

I'm going to publish v4.5.0 soon which could be your next try if you don't give up. Closing the issue since there is nothing I could do to fix it.

**Closed by vladimiry** 2020-05-19 20:21 UTC

**Comment by MoDzCatZ** [comment] 2020-05-20 09:24
Thanks I will try her right away.
And you would return.

On the other hand I do not have any antivirus apart from that of Windows where I check the quarantines and others, but I can not find anything as file delete

**Comment by vladimiry** [comment] 2020-05-20 09:28
If you know how to unpack the nins exe installer I think you could try taking the `sodium.node` from it and placing the file then into the folder you installed the app. The app-related  path is `./resources/app.asar.unpacked/node_modules/sodium-native/build/Release/sodium.node`.

**Comment by MoDzCatZ** [comment] 2020-05-20 10:56
![Screenshot_1](https://user-images.githubusercontent.com/2751766/82438248-069f5300-9a99-11ea-8063-7ff2f07ebb6e.png)


Always the same error.
The file was already present!
When in doubt I still replace it and always the same error there too.
I'm going to try to just decompress without installing and seeing.
I come back for a return

**Comment by MoDzCatZ** [comment] 2020-05-20 10:57
Even when decompressing I still have the same error!

**Comment by vladimiry** [comment] 2020-05-20 11:01
Ok, thanks for the update. If the file exists then it's a loaded issue which I don't yet have an idea how  deal with. The app uses 4 native modules but only `sodium-native` uses in my opinion too complex set of chained module loader rather than using simple approach.

**Comment by MoDzCatZ** [comment] 2020-05-20 11:36
Too bad it was a better alternative to protonmail desktop unificial.

But in my opinion, it is not an isolated problem that making the error on all Windows 10 1909.

In addition my installation is new.
Pity

**Comment by vladimiry** [comment] 2020-05-20 11:46
Btw @pzim-devdata managed to workaround the same issue before, see https://github.com/vladimiry/ElectronMail/issues/201#issuecomment-526862015.

**Comment by MoDzCatZ** [comment] 2020-05-20 12:17
I am downloading Visual Studio Pro 2015.
I already deactivate everything at Windows Defender level.

Once download and install, I will give you feedback.

**Comment by vladimiry** [comment] 2020-05-20 12:27
I guess installing https://chocolatey.org/packages/microsoft-visual-cpp-build-tools would make a similar effect but not sure since I'm not really use or build stuff on Windows.

**Comment by MoDzCatZ** [comment] 2020-05-20 16:56
So the installation is at the end.
Without having finished the installation, your application launches without error.

It must have missed a library or others on Windows 10 which prevents the execution of this one.

I will try to uninstall after VS 2015 to see if it is running or not.

But for those who have the same concern a VS installation is enough to unlock the error at launch

**Comment by vladimiry** [comment] 2020-05-20 17:09
Great news indeed. If you have time I'd interested you do the following test. Run the app in the way it gets failed with that error. Then save the sodium.node file somewhere (the original one). Then do that vs2015 hack, run the app and compare the sodium.node with original file. I just have a guess that maybe the file gets recompiled on your machine.

**Comment by MoDzCatZ** [comment] 2020-05-20 17:17
[sodium.zip](https://github.com/vladimiry/ElectronMail/files/4658351/sodium.zip)

**Comment by vladimiry** [comment] 2020-05-20 17:24
Thanks, files are the same. Then yes it looks like some runtime libraries were missed on your system. According to https://github.com/jedisct1/libsodium/issues/614 it could be `vcredist140.dll` library.

**Comment by MoDzCatZ** [comment] 2020-05-20 17:47
So here I uninstall VS2015 and after a restart with Windows Defender activate, everything works perfectly.

Thank you again for all the answers :)
And by precausion can be added to the file

**Comment by vladimiry** [comment] 2020-05-20 17:49
These are the vs2015/CRT-related libs I see to be loaded by the app in runtime:
- vcruntime140.dll, Microsoft® C Runtime Library
- ucrtbase.dll, Microsoft® C Runtime Library
- msvcrt.dll, Windows NT CRT DLL

**Comment by vladimiry** [comment] 2020-05-20 17:51
Thanks for not giving up, hope you like the app.

**Comment by vladimiry** [comment] 2020-05-20 18:10
I've just covered this issue in the [FAQ](https://github.com/vladimiry/ElectronMail/wiki/FAQ).
