### ISSUE TITLE
impossible to quit the windows when adding a picture.

### ISSUE THREAD

**Issue by dominix** [vladimiry/ElectronMail#338] opened 2020-10-19 20:56 UTC
when writing a new message and  when adding a picture, 
a window open to enter an url or a file and a comment for the picture.
from this point it is impossible to quit the window. 
Neither cancel nor quit nor validate the picture, nor button that close the window allow me to quit and to resume the writing of the message. So I stay stuck in the windows; I have to KILL the App and start again electron-mail.

**Comment by vladimiry** [comment] 2020-10-20 08:53
Same issue as 334?

CC @KaKi87.

**Comment by KaKi87** [comment] 2020-10-20 20:16
Oh, probably yes.

**Comment by vladimiry** [comment] 2020-10-20 20:20
Closing as duplicate of #334.

**Closed by vladimiry** 2020-10-20 20:20 UTC
