### ISSUE TITLE
Login Not Working

### ISSUE THREAD

**Issue by cjfortu** [vladimiry/ElectronMail#320] opened 2020-08-30 01:43 UTC
The 2FA input field times out after about 1-2 seconds - not enough time to delete the old code and enter the correct one. 

The manual login fields come up next.

The "Login" button is unresponsive here.

**Comment by vladimiry** [comment] 2020-08-30 08:58
I don't quite get what the issue is here I guess because I don't completely understand your workflow. It's designed in the way that if you have saved the 2FA secret token in the app then 2FA token will be automatically generated and submitted or you can input it manually if you don't save secret in the app.

**Comment by cjfortu** [comment] 2020-08-30 17:22
Ah yes.  It seems it was automatically submitting the 2FA token from the previous session (which was then expired).  So I had no chance to enter the updated token.  The manual login field which came up next, would then be unresponsive.

Of course, its working just fine now lol.  Might be an OS issue, I'm running Pop!_OS 20.04.  Will update if it happens again.

Thanks for the quick response.

**Comment by vladimiry** [comment] 2020-08-31 05:40
Closing for now then.

By the way Pop OS demonstrates other issue too, like #317.

**Closed by vladimiry** 2020-08-31 05:40 UTC
