### ISSUE TITLE
Version 4.2.0 keeps crashing

### ISSUE THREAD

**Issue by BobWs** [vladimiry/ElectronMail#241] opened 2020-01-28 09:07 UTC
Hi,
So I start testing your great developed desktop app for ProtonMail and it is looking greast so far.
But unfortunately updating to version 4.2.0 is not working, it keeps crashing on startup. 

First time I installed the latest version (4.2.0) but it was crashing immediately. Then I downloaded version (4.0.0) installed it and this version is working. Then I tried to update to version (4.2.0) and it keeps crashing.

I'm on OSX 10.13.6 (High Sierra)

Any thoughts how to solve this problem?

**Comment by vladimiry** [comment] 2020-01-28 09:18
@BobWs can you run the app from console with added `ELECTRON_ENABLE_LOGGING=true` environment variable and then see if there is something useful posted to console?

> Then I downloaded version (4.0.0) installed it and this version is working.

There are few possibly major macOS differences come with 4.2.0 in comparison with 4.0.0:
- 4.2.0 got upgraded @electron v6 => v7.
- 4.2.0 macOS package prepared on https://www.appveyor.com but previously was used https://travis-ci.org.

So these would be a points need to digged into first of all.

According to https://api.github.com/repositories/115260146/releases at the moment v4.2.0 macOS packaged got downloaded 107 times. So I wonder is there someone who runs macOS and gets v4.2.0 working well.

**Comment by vladimiry** [comment] 2020-01-28 09:32
e2e tests [got pasded on CI](https://ci.appveyor.com/project/vladimiry/electronmail/builds/30351201/job/bww04e860tjdd397#L1209) so I guess the problem happen only with packed version. On CI e2e tests executed before the app got packed.

**Comment by vladimiry** [comment] 2020-01-28 09:53
> 4.2.0 macOS package prepared on https://www.appveyor.com

According to https://www.appveyor.com/docs/macos-images-software/ the `macos` image is based on macOS 10.15 "Catalina" and XCode 11.2.1 (the app goes with [macos](https://github.com/vladimiry/ElectronMail/blob/5bc43682b0fb761729823060310667ab329926c6/appveyor.yml#L31) image).
<details><summary>npx envinfo output</summary>

Link: https://ci.appveyor.com/project/vladimiry/electronmail/builds/30351201/job/bww04e860tjdd397#L67

```
npx: installed 1 in 0.922s
  System:
    OS: macOS 10.15.1
    CPU: (2) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
    Memory: 93.79 MB / 2.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    Yarn: 1.21.1 - ~/.yarn/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
  Managers:
    Homebrew: 2.1.16 - /usr/local/bin/brew
    pip3: 19.3.1 - /usr/local/bin/pip3
    RubyGems: 3.0.6 - /Users/appveyor/.rvm/rubies/ruby-2.6.3/bin/gem
  Utilities:
    CMake: 3.16.0 - /usr/local/bin/cmake
    Make: 3.81 - /usr/bin/make
    GCC: 11.2.1. - /usr/bin/gcc
    Git: 2.24.0 - /usr/local/bin/git
    Clang: 1100.0.33.12 - /usr/bin/clang
    Mercurial: 5.2 - /usr/local/bin/hg
    Subversion: 1.13.0 - /usr/local/bin/svn
  Servers:
    Apache: 2.4.41 - /usr/sbin/apachectl
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Nano: 2.0.6 - /usr/bin/nano
    Vim: 8.1 - /usr/bin/vim
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Go: 1.13.4 - /Users/appveyor/.gvm/gos/go1.13.4/bin/go
    Java: 13.0.1 - /usr/bin/javac
    Perl: 5.30.0 - /usr/local/bin/perl
    PHP: 7.3.9 - /usr/bin/php
    Python: 2.7.16 - /usr/bin/python
    Python3: 3.7.5 - /usr/local/bin/python3
    Ruby: 2.6.3 - /Users/appveyor/.rvm/rubies/ruby-2.6.3/bin/ruby
  Databases:
    SQLite: 3.28.0 - /usr/bin/sqlite3
  Browsers:
    Safari: 13.0.3
```

</details>

>  but previously was used https://travis-ci.org.

Here macOS High Sierra 10.13.6 and XCode 9.4 was used.

<details><summary>npx envinfo output</summary>

Link: https://travis-ci.org/vladimiry/ElectronMail/jobs/627583668#L168

```
$ npx envinfo

npx: installed 1 in 1.321s
  System:
    OS: macOS High Sierra 10.13.6
    CPU: (2) x64 Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz
    Memory: 1.51 GB / 4.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.4.0 - ~/.nvm/versions/node/v12.4.0/bin/node
    Yarn: 1.21.1 - ~/.yarn/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.4.0/bin/npm
  Managers:
    CocoaPods: 1.8.4 - /Users/travis/.rvm/gems/ruby-2.6.3/bin/pod
    Homebrew: 2.2.1 - /usr/local/bin/brew
    Maven: 3.6.3 - /usr/local/bin/mvn
    pip2: 19.3.1 - /usr/local/bin/pip2
    pip3: 19.3.1 - /usr/local/bin/pip3
    RubyGems: 3.0.3 - /Users/travis/.rvm/rubies/ruby-2.6.3/bin/gem
  Utilities:
    CMake: 3.15.5 - /usr/local/bin/cmake
    Make: 3.81 - /usr/bin/make
    GCC: 9.4.1. - /usr/bin/gcc
    Git: 2.24.1 - /usr/local/bin/git
    Clang: 902.0.39.2 - /usr/bin/clang
    Mercurial: 5.2 - /usr/local/bin/hg
    Subversion: 1.9.7 - /usr/bin/svn
  Servers:
    Apache: 2.4.33 - /usr/sbin/apachectl
  SDKs:
    iOS SDK:
      Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
  IDEs:
    Emacs: 22.1.1 - /usr/bin/emacs
    Nano: 2.0.6 - /usr/bin/nano
    Vim: 8.0 - /usr/bin/vim
    Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Go: 1.13.4 - /usr/local/bin/go
    Java: 13.0.1 - /usr/bin/javac
    Perl: 5.18.2 - /usr/bin/perl
    PHP: 7.1.16 - /usr/bin/php
    Python: 2.7.17 - /usr/local/bin/python
    Python3: 3.7.5 - /usr/local/bin/python3
    Ruby: 2.6.3 - /Users/travis/.rvm/rubies/ruby-2.6.3/bin/ruby
  Databases:
    PostgreSQL: 12.1 - /usr/local/bin/postgres
    SQLite: 3.19.3 - /usr/bin/sqlite3
```

</details>

**Comment by vladimiry** [comment] 2020-01-28 09:57
@BobWs 

> This looks like a huge difference in general which though I'm not sure is supposed to affect the package preparing process.

What I could do for now is preparing the 4.2.0 package on Travis CI like it was happening before and then we see if it helps.

**Comment by vladimiry** [comment] 2020-01-28 13:36
By the way, can someone, like @joshirio / @Imparium / @andrewkdinh / @BBaoVanC / @bit-for-byte / @ylluminate respond with v4.2.0 running status on macOS if you tried this release already (please include the used macOS version in response)? Does it crash?

**Comment by BobWs** [comment] 2020-01-28 15:09
> @BobWs can you run the app from console with added `ELECTRON_ENABLE_LOGGING=true` environment variable and then see if there is something useful posted to console?

Sorry, but I'm not quite sure what you mean and how I'm suppose to do that?

**Comment by BobWs** [comment] 2020-01-28 15:20
I have found this in the console logs from yesterday when I tried to install version 4.2.0:

`Process:               ElectronMail [877]`
`Path:                  /Applications/ElectronMail.app/Contents/MacOS/ElectronMail`
`Identifier:            github.comvladimiryElectronMail`
`Version:               4.2.0 (4.2.0.298)`
`Code Type:             X86-64 (Native)`
`Parent Process:        ??? [1]`
`Responsible:           ElectronMail [877]`
`User ID:               501`
`Date/Time:             2020-01-27 10:36:54.436 +0100`
`OS Version:            Mac OS X 10.13.6 (17G65)`
`Report Version:        12`
`Anonymous UUID:        AA502188-D46F-8C6D-5AA3-908CA9F96746`
`Time Awake Since Boot: 4600 seconds`

`System Integrity Protection: enabled`

`Crashed Thread:        22`

`Exception Type:        EXC_CRASH (SIGKILL)`
`Exception Codes:       0x0000000000000000, 0x0000000000000000`
`Exception Note:        EXC_CORPSE_NOTIFY`

`Termination Reason:    DYLD, [0x4] Symbol missing`

`Dyld Error Message:`
  `Symbol not found: ____chkstk_darwin`
  `Referenced from:` `/Applications/ElectronMail.app/Contents/Resources/app.asar.unpacked/node_modules/sodium-native/build/Release/libsodium.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib`

**Comment by vladimiry** [comment] 2020-01-28 15:30
@BobWs, thanks, this is helpful.

> Dyld Error Message:
Symbol not found: ____chkstk_darwin
Referenced from: /Applications/ElectronMail.app/Contents/Resources/app.asar.unpacked/node_modules/sodium-native/build/Release/libsodium.dylib (which was built for Mac OS X 10.15) Expected in: /usr/lib/libSystem.B.dylib

`libsodium` is a native library the app uses for encryption needs. For v4.2.0 release it was compiled fro sources on `macOS 10.15 Catalina and XCode 11.2.1` environment but apparently should be compiled on the macOS version you run the app. So I'm going to prepare DMG packages assembled on different macOS versions and then will ask you to try all of them.

**Comment by joshirio** [comment] 2020-01-28 16:36
> By the way, can someone, like @joshirio respond with v4.2.0 running status on macOS if you tried this release already (please include the used macOS version in response)? Does it crash?

yes I can confirm same crash on macOS high sierra

**Comment by vladimiry** [comment] 2020-01-28 17:38
Ok, then v4.2.0 presumably starts without  crash only on Catalina and possibly on Mojave (not confirmed yet).

**Comment by andrewkdinh** [comment] 2020-01-28 18:02
ElectronMail 4.2.0 works fine for me

macOS Catalina 10.15.2

**Comment by vladimiry** [comment] 2020-01-29 06:58
@BobWs, can you try running the `electron-mail-4.2.1-mac-high-sierra.dmg` package uploaded [here](https://mega.nz/#F!hoRBRY6J!MOmt8PoOoWU2Sv1j-JzC3g)? Anyone else is also welcomed to try the updated macOS packages. If it works well I then will be preparing the v4.2.1 release.

**Comment by BobWs** [comment] 2020-01-29 07:57
> @BobWs, can you try running the `electron-mail-4.2.1-mac-high-sierra.dmg` package uploaded [here](https://mega.nz/#F!hoRBRY6J!MOmt8PoOoWU2Sv1j-JzC3g)? Anyone else is also welcomed to try the updated macOS packages. If it works well I then will be preparing the v4.2.1 release.

Thanks for the quick response and update I will give it a try and get back to you. 

Just another question, did you drop the Tutanota support in the app? Because I couldn’t find the ability to add an Tutanota account. I only have the ability to add
ProtonMail.

**Comment by vladimiry** [comment] 2020-01-29 08:44
> Just another question, did you drop the Tutanota support in the app?

Tutanota was [deprecated since July 2019](https://github.com/vladimiry/ElectronMail/issues/180). The visual/in-the-app deprecation message added in Sep 2019 with [v3.8.0](https://github.com/vladimiry/ElectronMail/releases/tag/v3.8.0). Support for it got completely dropped in [v4.0.0](https://github.com/vladimiry/ElectronMail/releases/tag/v4.0.0).

**Comment by BobWs** [comment] 2020-01-29 08:45
I can confirm that the update (electron-mail-4.2.1-mac-high-sierra) is working properly no crashes. Thanks!

**Comment by vladimiry** [comment] 2020-01-29 08:46
Great, new release in on the way then.

**Comment by BobWs** [comment] 2020-01-29 08:48
> > Just another question, did you drop the Tutanota support in the app?
> 
> Tutanota support was [deprecated since July 2019](https://github.com/vladimiry/ElectronMail/issues/180). The visual/in-the-app deprecation message added in Sep 2019 with [v3.8.0](https://github.com/vladimiry/ElectronMail/releases/tag/v3.8.0). Support for it got completely dropped in [v4.0.0](https://github.com/vladimiry/ElectronMail/releases/tag/v4.0.0).

Okay, Sorry I overlooked the changelog ;-)

**Comment by vladimiry** [comment] 2020-01-29 11:20
[v4.2.1](https://github.com/vladimiry/ElectronMail/releases/tag/v4.2.1) has been released with the fix included. Since this release assets list include nto just one but 3 macOS packages:
-  electron-mail-x.x.x-mac-catalina.dmg
- electron-mail-x.x.x-mac-high-sierra.dmg
- electron-mail-x.x.x-mac-mojave.dmg

**Closed by vladimiry** 2020-01-29 11:20 UTC
Labels: crash
