### ISSUE TITLE
Can't access ProtonDrive

### ISSUE THREAD

**Issue by IberratioActus** [vladimiry/ElectronMail#417] opened 2021-07-09 05:19 UTC
I have a paid subscription on my account and can access ProtonDrive on my browsers, but whenever I try to access it vía the ElectronMail app, it just gives me the message that I need a sub in order to use it.

Is there an issue on my end maybe?

**Comment by vladimiry** [comment] 2021-07-09 05:21
Duplicate of #377.

**Closed by vladimiry** 2021-07-09 05:21 UTC
