### ISSUE TITLE
Feature request: ability to export the entire mailbox to an MBOX file

### ISSUE THREAD

**Issue by ContentPersonality2** [vladimiry/ElectronMail#293] opened 2020-05-14 14:37 UTC
At the moment you can batch export each email to an EML file however this makes browsing exported emails quite difficult without the use of ElectronMail. Google exports its mailbox to an MBOX file which contains all emails in one file which can be opened with apps like [MBOX viewer](https://github.com/eneam/mboxviewer). It makes browsing you emails easy while offline which in-turn makes it possible to easily browse archived emails that have been deleted from their original home in the cloud.

**Comment by vladimiry** [comment] 2020-05-14 18:14
The available workaround is to import EML files into the local folder in Thunderbird using https://addons.thunderbird.net/en-US/thunderbird/addon/importexporttools-ng/ or similar extension.

**Comment by ContentPersonality2** [comment] 2020-05-16 11:58
> The available workaround is to import EML files into the local folder in Thunderbird using https://addons.thunderbird.net/en-US/thunderbird/addon/importexporttools-ng/ or similar extension.

When I open the EML files in Thunderbird I'm told the attachments are empty. Is this an issue with ElectronMail not exporting correctly or Thunderbird not importing correctly?

**Comment by vladimiry** [comment] 2020-05-16 18:44
ElectronMail by design doesn't sync/store the attachments and so it doesn't export them too. It only keeps the file names and size for the full-text search purposes but not the content. Enabling attachments support is not planned for the near future.

**Comment by ContentPersonality2** [comment] 2020-05-19 14:03
> ElectronMail by design doesn't sync/store the attachments and so it doesn't export them too. It only keeps the file names for the full-text search purposes but not the content. I just made it more clear by [c629531](https://github.com/vladimiry/ElectronMail/commit/c6295310ff0ff0f0ec8a38bfc13b2c8e4d81a40d). Enabling attachments support is not planned for the near future.

I'd love to see the ability to export attachments too even if it was an opt-in. Either way I can't complain as this app is free and I'm very appreciative for you making it and helping people with issues so quickly, thanks dude!

Feel free to close this issue to archive it if you'd like.

**Comment by vladimiry** [comment] 2020-05-19 16:45
Downloading the attachments to store them offline and encrypted in the way it doesn't badly affect the app performance and memory consumption would be a huge effort but technically possible. Besides, enabling the feature here would significantly increase the load on protonmail's servers. So closing the issue for now since I'm not going to jump into the building the requested feature in the near future.

**Closed by vladimiry** 2020-05-19 16:45 UTC

**Comment by vladimiry** [comment] 2020-07-25 21:19
v4.7.0 is going to optionally enable the live attachments loading during the export process. So full batch export will be happening, including the attachments content.

**Comment by Jelmerro** [comment] 2022-10-04 13:04
Sorry to hijack an old issue like this, but since attachments are exported flawlessly with your cool app nowadays, is there any chance to reconsider exporting to mbox? If not, feel free to leave this issue closed. I would have opened a new issue for it if I didn't find this one, and am still willing to do so if desired. Thanks for building ElectronMail, I couldn't use protonmail without it :+1:

**Comment by vladimiry** [comment] 2022-10-04 14:00
@Jelmerro, it's still "won't fix". Thanks for the feedback.

**Comment by Jelmerro** [comment] 2022-10-04 14:09
Thanks for the fast response. I just thought that mbox would be easier now that attachments are no longer a blocker for this, but I understand that it's still more work to build. Even just having the EML export is awesome enough.
