### ISSUE TITLE
ProtonDrive unavailable

### ISSUE THREAD

**Issue by shdwchn10** [vladimiry/ElectronMail#377] opened 2021-02-27 18:29 UTC
When I open ProtonDrive I get this error:
![screenshot](https://user-images.githubusercontent.com/79763381/109396362-0c2fa080-7929-11eb-9417-6b46a77ddd90.png)

ProtonDrive in Firefox works.
I tried to remove all ElectronMail data (`rm -rf ~/.var/app/com.github.vladimiry.ElectronMail`) and login again but it didn't help.

Proton Subscription: Visionary
ElectronMail version: v4.10.2 (Flatpak)
OS: Fedora Silverblue 33

**Comment by vladimiry** [comment] 2021-02-27 18:36
There is not a lot I can do about ProtonDrive since I don't have accounts with enabled access to this service. What at the moment is done regarding ProtonDrive is just packing the respective @protonmail web client into the app.

**Comment by vladimiry** [comment] 2021-02-27 18:38
> When I open ProtonDrive I get this error:

That doesn't look like an error but a warning saying that your account doens't have the access to the service yet.

**Comment by BenMMcLean** [comment] 2021-03-01 03:23
I also experience the error, but my account does have access to ProtonDrive through my browser

**Comment by vladimiry** [comment] 2021-03-01 07:34
Marking the issue as a bug then but won't be doing anything to fix it until I get access to the ProtonDrive service.

**Comment by vladimiry** [comment] 2021-03-03 13:19
I did a brief debugging and have noticed that there is no `is-paid-user=1` cookie set in the app when the `/api/drive/shares` API gets requests (this API call depending on the outcome triggers the demonstrated warning displaying). The reason is that @electron doesn't work well with the JS-based cookies for the pages loaded on `file://` or custom schemes. Not saying yet that this is the issue cause but the difference in comparison with a regular browser use.

**Comment by vladimiry** [comment] 2021-07-09 05:35
Another possible reasons is that in browser you signing via @protonmail the SSO but in the app that SSO thing is not used by design. I've approached @protonmail regarding the issue but they were not helpful so far.

**Comment by xyz-nobody** [comment] 2021-07-10 07:09
I have exactly the same problem but with a different error message.

However, if I connect directly without going through electron-mail I have full access to protondrive.



![bug](https://user-images.githubusercontent.com/6586244/125155159-84b33300-e14d-11eb-82be-d29ce9158a35.png)

**Comment by TheCultLeader666** [comment] 2021-11-28 16:01
Same issue here, says I need to upgrade, while I already own a visionary account.

**Comment by vladimiry** [comment] 2021-11-28 16:12
I assumed in https://github.com/vladimiry/ElectronMail/issues/377#issuecomment-876927077 that Drive service is designed to be only available for users who have signed in into the account via the SSO login scenario. @mmso can you or someone on the team confirm or deny this assumption? СС @bartbutler.

**Comment by Dvlnst** [comment] 2022-03-23 19:56
I received a mail confirming Proton Drive is already available in beta for free users (maybe just a soft release at this moment). Could you please check it out again? I would love to have Proton Drive in my desktop.

Cheers.

**Comment by Dvlnst** [comment] 2022-04-12 14:40
I'm back to confirm that Protondrive is working for me. It seems they have fixed the login process for this service!

Thanks to @vladimiry for all the work he is doing with this app.

Cheers.

**Comment by vladimiry** [comment] 2022-04-12 14:45
@Dvlnst thanks for observing the Protondrive availability in the app and putting the update here. So apparently @protonmail has finally fixed the above-mentioned "access scope"-related issue. Closing the issue as resolved.

**Closed by vladimiry** 2022-04-12 14:45 UTC
Labels: bug, provider change: api/backend, upstream, proton-drive
