### ISSUE TITLE
Left clicking tray icon not working even with Tray Icons: Reloaded

### ISSUE THREAD

**Issue by Gieted** [vladimiry/ElectronMail#379] opened 2021-03-01 00:42 UTC
Related: #94

I know it's a known issue, but using [Tray Icons: Reloaded](https://extensions.gnome.org/extension/2890/tray-icons-reloaded/) Gnome extension seems to fix it for all electron-based apps except **ElectronMail**. 

Some examples are:
- Discord
- signal-dekstop
- Caprine

I'm don't know any details, but hope you'll give it a look.

**Comment by vladimiry** [comment] 2021-03-01 08:03
> Related: #94

After changing the tray icon implementation in v8 @electron reverted the change back and so the click on tray icon got broken again.

Even if it works on some environments, like Gnome + Tray Icons: Reloaded (which I have not verified myself), it doesn't work for other kinds of desktop environments. I have just tested Discord not using the Xfxe environment and the issue is still there. The Signal doesn't show any tray icon at all.

So this is an upstream issue which need to be fixed by @electron.

**Closed by vladimiry** 2021-03-01 08:03 UTC
