### ISSUE TITLE
"Error: Opening a new window is forbidden" when clicking links

### ISSUE THREAD

**Issue by CorruptComputer** [vladimiry/ElectronMail#285] opened 2020-04-26 18:55 UTC
Sometimes when clicking links in emails I get the following error:
![image](https://user-images.githubusercontent.com/5573038/80316763-41c5a380-87c5-11ea-9e14-3c212b1be3c6.png)
```
Unhandled Error
Error: Opening a new window is forbidden, url: "https://rt.linuxfoundation.org/"
    at notifyLogAndThrow (C:/Program Files/ElectronMail/resources/app.asar/app/electron-main.js:6466:19)
    at WebContents.<anonymous> (C:/Program Files/ElectronMail/resources/app.asar/app/electron-main.js:6479:13)
```

Clicking it again it usually goes away and works fine, but I'm not sure what the cause is.

**Comment by vladimiry** [comment] 2020-04-26 19:03
The error message you see is a result of additional security check took place. Normally it should not happen but some links are tricky to intercept the clicking of. So the reason for the issue is that the link clicking interception logic implemented in the app has room for improvement.

**Comment by vladimiry** [comment] 2020-04-26 19:15
I thing the simple to implement solution for this issue would be in opening an the link as external / in-browser instead of raising the error.

**Comment by CorruptComputer** [comment] 2020-04-26 19:34
I just figured out an easy way to cause it on every click. If you middle-click (to open in a new tab) it will cause this.

I have a habit of doing this when on the web, so this may have just been user error sometimes with muscle memory doing middle-click on the links instead of left-click.

**Comment by vladimiry** [comment] 2020-04-26 19:41
This is a good finding. Adding middle click handler plus the change from my previous message should resolve the issue.

**Comment by vladimiry** [comment] 2020-04-26 20:46
The fix has been implemented and will be included in the next release.

**Closed by vladimiry** 2020-04-26 20:46 UTC
Labels: bug

**Comment by CorruptComputer** [comment] 2020-04-26 20:55
Amazing, thank you!
