### ISSUE TITLE
[NEWS] official proton mail desktop app in 2024

### ISSUE THREAD

**Issue by pirate486743186** [vladimiry/ElectronMail#664] opened 2023-12-16 07:43 UTC
@vladimiry 
In case you didn't know
https://proton.me/support/mail-desktop-app
It's in restricted beta now, it will be freely available beta in a few months.

What do you plan on doing?

Maybe, now you could transplant the brains of both proton mail and tutanota in one app?
Or you simply shut down electron-mail?

**Comment by vladimiry** [comment] 2023-12-16 10:01
Some thoughts were shared in #650. Generally, based on a brief private communication with them and some code highlighted in #650, I knew their electron-based app is coming.

> Maybe, now you could transplant the brains of both proton mail and tutanota in one app?

The app originally was designed to be able to support multiple email providers. Originally, Tutanota support was here, including support for offline access to the emails, but then it got cut out from the app, and it's not getting back. One could think, that the reason is that they rolled out their one desktop app, but that was not the only reason and not the primary one.

>  Or you simply shut down electron-mail?

Shutting it down, "archiving" the project in terms of GitHub, closing the project updates for public, might happen, but it's not there yet. The primary reason is that I still use ElectronMail since it still fulfills my needs. Besides, there are some features in ElectronMail I use, that I don't believe the official app is going to provide.

**Closed by vladimiry** 2023-12-16 10:01 UTC

**Comment by vladimiry** [comment] 2023-12-20 04:35
As said before, ElectronMail still fulfills my needs, so starting a new open source project is not happening in the near future, especially if it's related to Tutanota.
