### ISSUE TITLE
Update Logo for a modern one

### ISSUE THREAD

**Issue by LawOff** [vladimiry/ElectronMail#546] opened 2022-08-21 19:36 UTC
Hey, the whole design of Proton has changed, and I thought that changing the logo of the app would be the right time, I suggest you this one:

https://i.imgur.com/nAq9zEV.png

<img src="https://i.imgur.com/nAq9zEV.png?v=3" width="400" />

**Comment by vladimiry** [comment] 2022-08-21 19:37
Dupe of #539.

**Closed by vladimiry** 2022-08-21 19:37 UTC
