### ISSUE TITLE
Message doesnt exist

### ISSUE THREAD

**Issue by babebort** [vladimiry/ElectronMail#713] opened 2024-11-06 15:43 UTC
I don't know how to reproduce it, It appears from time to time, seems like it's not from API response, is it an ElectronMail issue?

![image](https://github.com/user-attachments/assets/71f51fbc-0bed-45b2-9a23-59d45ea66dbf)

**Comment by vladimiry** [comment] 2024-11-06 16:51
This turns out to be duplicate of #661.

**Closed by vladimiry** 2024-11-06 16:51 UTC
