### ISSUE TITLE
"The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called."

### ISSUE THREAD

**Issue by xynder** [vladimiry/ElectronMail#163] opened 2019-06-11 12:38 UTC
Getting this error after entering EM master password and beginning login to Protonmail.  It doesn't seem to affect anything, just wondering how I can prevent it.

**Comment by vladimiry** [comment] 2019-06-11 12:44
Thank for the report.

The following info would be needed for the investigation:
- App version.
- Installation package used (like full file name you installed the app or the repository link).
- OS name and version used.
- `log.log` file located in the [setting folder](https://github.com/vladimiry/ElectronMail/blob/master/images/open-settings-folder.jpg).

If you prefer you can send the requested data privately to the email specified in the `author` section [here](https://github.com/vladimiry/ElectronMail/blob/master/package.json#L5).

**Comment by vladimiry** [comment] 2019-06-12 12:28
@xynder can you try the recently released v3.5.0? Then please either confirm that the issue is resolved with the new version or send me the log file again.

**Comment by xynder** [comment] 2019-06-12 13:16
just installed it thank you, i'll let you know.

question -- is there any easy way to update in the future?  i had installed 3.4 from Snap store and wasnt getting an update prompt when I ran 3.4, so I downloaded 3.5 (.deb) from the github and installed, but this ended up installing another copy in addition to 3.4, so I had to remove 3.4 and start over with 3.5.  in the future whats the fastest way to just update it?

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by vladimiry** [comment] 2019-06-12 13:37
> is there any easy way to update in the future?

The Snap Store repository is being maintained by @joshirio and it's up to date. I'd recommend waiting until your system noticed the update rather than installing the second app version (there might be a way to force it somehow, likу rebooting the system?). Besides the issue originally occurred with a Snap build so it's better to test the updated Snap version.

**Comment by joshirio** [comment] 2019-06-12 15:15
> there might be a way to force it somehow, likу rebooting the system?

`sudo snap refresh` should do it

**Comment by xynder** [comment] 2019-06-12 23:43
Got it thanks all!

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by vladimiry** [comment] 2019-06-19 09:34
Closing inactive issue.

**Closed by vladimiry** 2019-06-19 09:34 UTC
