### ISSUE TITLE
Attachments

### ISSUE THREAD

**Issue by RobertKirchner9** [vladimiry/ElectronMail#516] opened 2022-05-27 02:43 UTC
I've begun to have problems with attachments within ElectronMail. The navigation window opens but it won't let me navigate out of the home folder, and it won't actually upload or download the file. I'm running Linux Mint Mate 20.3.

**Comment by vladimiry** [comment] 2022-05-27 08:43
Can you describe the exact steps, so I could reproduce the issue?

Btw, if you run flatpak build, then attachment files selection dialog restriction to the `home/downloads` folder is expected behavior. This restriction was introduced by design for the flatpak app version from day one in order to improve isolation and so the privacy/security.

Besides, yesterday @protonmail started deploying to production a major v5 upgrade of web clients and likely some backend services. So if it stopped working for you just recently without app update, then this @protonmail upgrade might be a reason since the packaged into the app web client possibly got outdated (not synced with the upgraded backend services).

**Comment by RobertKirchner9** [comment] 2022-05-27 23:57
I don't have the flatpak build, but the ProtonMail upgrade sounds a likely cause.

Let's just address the uploading problem first. I'm sure I hit the paper clip attachment icon toward the bottom of the compose window. I'm given options (Recent, Home, Desktop, other locations) but in none of them do any files whatsoever appear. I can navigate from Recent to Home, but when I click on Desktop, nothing happens. But not even in the Home folder do I see any files.

Sent with [ProtonMail](https://protonmail.com/) secure email.

------- Original Message -------

**Comment by vladimiry** [comment] 2022-05-28 00:00
What is the way you installed the app? The described behavior looks very similar to how flatpak app package type is designed to work.

**Comment by RobertKirchner9** [comment] 2022-05-28 00:23
Ah, it is Flatpak. From the Mint Software Manager. Where else can I download it from, for a non Flatpak build?

Sent with [ProtonMail](https://protonmail.com/) secure email.

------- Original Message -------

**Comment by vladimiry** [comment] 2022-05-28 00:26
- DEB package on https://github.com/vladimiry/ElectronMail/releases page should work on Ubuntu-based systems (like Linux Mint Mate).
- You could also try the Snap version https://snapcraft.io/electron-mail.

**Comment by vladimiry** [comment] 2022-05-30 07:46
There is nothing to fix (flatpak package works the described way by design), so closing as addressed.

**Closed by vladimiry** 2022-05-30 07:46 UTC

**Comment by vladimiry** [comment] 2022-05-30 10:55
I missed note, if you would like to keep using flatpak version of the app, you could let the app access any file systems resources using https://flathub.org/apps/details/com.github.tchx84.Flatseal app. Flatseal allows overriding the permissions for the flatpak apps. Quite convenient.
