### ISSUE TITLE
Make left-clicking the tray icon always "toggle window"? (at least on Linux, no idea about Windows)

### ISSUE THREAD

**Issue by NintendoManiac64** [vladimiry/ElectronMail#514] opened 2022-05-10 18:56 UTC
Currently, at least on my installation of Linux Mint 20.3 XFCE, left-clicking the tray icon does the exact same thing as right clicking.

I would think that it would make more sense that left-clicking would simply always activate the "toggle window" action while right-click can be used for the pop-up context menu (other programs such as nheko behave in such a manner).

**Comment by vladimiry** [comment] 2022-05-10 19:05
This is a well-known and long-standing issue of @electron, see https://github.com/electron/electron/issues/14941.

This issue is basically a duplicate of #379 and #94, but I will keep it open, so it's more clear that the issue is known.

**Comment by vladimiry** [comment] 2022-11-30 20:27
Electron v22 gets back [StatusNotifierItem](https://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/)-based tray icon logic. So the issue is going to be fixed with the next app release.

**Closed by vladimiry** 2022-11-30 20:27 UTC
Labels: upstream, user-experience, env: linux
