### ISSUE TITLE
bug: electronmail logo is visibly corrupted at lower resolutions on macOS

### ISSUE THREAD

**Issue by kittywhiskers** [vladimiry/ElectronMail#361] opened 2021-01-17 05:13 UTC
## Expected Behavior

Successful rendering of the ElectronMail logo at various resolutions

## Actual Behaviour

Glitching of the ElectronMail logo at lower resolutions (behavior can also be reproduced by using Launchpad and placing ElectronMail in a folder and then exiting that folder, previewing the lower resolution ElectronMail icon)

![ElectronMail using Spotlight](https://user-images.githubusercontent.com/63189531/104831593-6b24e300-58b0-11eb-9e43-b97939c13b5f.png)

**Comment by vladimiry** [comment] 2021-01-17 08:13
Thanks for the detailed report. Closing as duplicate of #283. It's up to @electron to fix it. Besides I don't have macOS devices at hand so can't test stuff if I would be trying to find a workaround.

**Closed by vladimiry** 2021-01-17 08:13 UTC
