### ISSUE TITLE
I have a simple question about CMD line

### ISSUE THREAD

**Issue by goldpooh** [vladimiry/ElectronMail#498] opened 2022-03-24 08:05 UTC
Hello, vladimiry! 

I am very happy to know you on this world.

I thank you for your help, But I need your important help.

Umm... I executed a following command line for ElectronMail by myself.

Command line Ex:  
open -n -a ElectronMail.app --args -compose to='******@protonmail.com',from='******@outlookmail.com',subject='news',
body='<br/>Hello. How is your work going?<br/>I have some news to share with you.<br/>I am pretty sure you will be glad for these.<br/>Please check them out.<br/>Good Luck.<br/>',attachment=' '

When I executed Up CMD line, ElectronMail was executed automatically, but in ElectronMail New Message window was not appeared.
 
This CMD line is for  Mac OS, but this CMD line was not executed for ElectronMail

If you have a good think, I hope you send me your opinion.

Thanks, dear vladimiry

**Comment by vladimiry** [comment] 2022-03-24 08:09
Dupe of #496.

**Closed by vladimiry** 2022-03-24 08:09 UTC
