### ISSUE TITLE
[4.13.2] hChaptcha display problem

### ISSUE THREAD

**Issue by mastino21** [vladimiry/ElectronMail#488] opened 2022-02-11 07:48 UTC
Latest version, either in Windows and Linux (Opensuse TW, AppImage).

When trying to add a new account that triggers hChaptcha prompt, that prompt appears but it's blank. See screenshot.
Tested on two different networks.

![Screenshot from 2022-02-11 08-46-39](https://user-images.githubusercontent.com/64143442/153554610-18b0ecba-edd8-4efd-88f0-059c7676ef8d.png)

**Comment by vladimiry** [comment] 2022-02-11 07:51
Dupe of #419 (upstream/proton's issue).

**Closed by vladimiry** 2022-02-11 07:51 UTC
