### ISSUE TITLE
App crash with /api/data/v1/metrics resolving error

### ISSUE THREAD

**Issue by GoldenGlimpse** [vladimiry/ElectronMail#696] opened 2024-09-07 12:05 UTC
The app crashes when trying to upload to drive. Or trying to open Calendar from right side pane.

**Reproduce:**
Upload a file --> crash.
or
Click on Calendar in right side pane --> crash.

**Error:**
```
Unhandled Promise Rejection
Error: Failed to resolve file system resource directory from the "webclient://calendar.proton.me/mail" request
    at resolveFileSystemResourceLocation (/opt/ElectronMail/resources/app.asar/app/electron-main/index.cjs:76421:57)
    at AsyncFunction.<anonymous> (/opt/ElectronMail/resources/app.asar/app/electron-main/index.cjs:76455:42)
```

**Version:**
ElectronMail v5.2.3
**System:**
Linux Mint 21.3, Ubuntu 22.04 jammy.

**Comment by vladimiry** [comment] 2024-09-07 13:02
> Or trying to open Calendar from right side pane.

This is not supposed to work in the app, see the pinned #579. I should consider cutting out the related icon from the right panel to reduce confusion.

> The app crashes when trying to upload to drive.

Could not reproduce on a short plain text file, but will try again later on something bigger. More details from you regarding file size/type might help with issue reproduction.

**Comment by GoldenGlimpse** [comment] 2024-09-07 13:45
It happens pretty much with any file. I tried uploading a plain 10mb mp3 file. It uploads, it finishes, and 3 seconds later the app crashes with the same error box. 
Even tested with a 14kb docx file, same thing.

> This is not supposed to work in the app,

I know, but it used to show a blank error page. Now the app crashes and i have to reopen Electron and log back in.

**Comment by vladimiry** [comment] 2024-09-07 14:11
Thanks for more info. The error occurs during `/api/data/v1/metrics` API fetch call, so I guess all the calls to this API will be triggering app crash. A brief look into it, aside from the Drive, also revealed some more `/api/data/v1/metrics` API uses in Account app during the signup flow, so I guess it might be impossible to create the account in the app (I didn't test the case yet). There were a bunch of redirection/resource-resolving errors I handled by [patching](https://github.com/vladimiry/ElectronMail/tree/master/patches/protonmail), but this one I missed to notice.

**Comment by vladimiry** [comment] 2024-10-09 07:23
Can you test the build shared in https://github.com/vladimiry/ElectronMail/issues/694#issuecomment-2400871180? It comes with up-to-date Drive web client, and so maybe it gets better in some way.

**Comment by vladimiry** [comment] 2024-11-07 15:45
At this time, I'm not aware of the exact purpose of the Metrics service and the respective API calls, like `/api/data/v1/metrics`. But I'm going to cut this stuff out from the app, like done in 81e9df973579124c7939deec9f149c35da1322d9 (wiping public methods of the `MetricsRequestService` service), and see what happens.

I don't know whom I could ping from the Proton team as someone who might be willing to shed some light on the Metrics purpose and if it really required for the core web apps functionality, maybe @mmso could help?

**Comment by mmso** [comment] 2024-11-07 15:49
Purposes are purely informational. Yeah sounds good to me.

**Comment by vladimiry** [comment] 2024-11-07 15:52
> Purposes are purely informational. Yeah sounds good to me.

Thanks a lot for confirming a guess.

**Comment by vladimiry** [comment] 2024-11-07 21:40
> as a simple solution, I'm going to cut this stuff out from the app, like done in 81e9df973579124c7939deec9f149c35da1322d9 (wiping public methods of the `MetricsRequestService` service), and see what happens.

The build with the implemented change is available [here](https://mega.nz/folder/4swj3LjD#oOzGmNLeQrmO6WNeJ4ivGg). Closing the issue as resolved.

**Closed by vladimiry** 2024-11-07 21:40 UTC
Labels: crash
