### ISSUE TITLE
Very long loading time after completing an action (like deleting some mails)

### ISSUE THREAD

**Issue by koopernick** [vladimiry/ElectronMail#325] opened 2020-09-09 09:30 UTC
Hello,

First of all, thank you for your work.

I'm facing an issue for the past couple of releases (not sure exactly when it started).
When I'm switching folders (like inbox, or any folder I have, etc), it's fast without any issue.

As soon as I delete some mails from a folder (doesn't matter which one), the loading of any other folder takes forever. It's just loading for 15-20 sec and then it displays the content of the folder. The reload of the same folder, after deleting is also impacted.

I didn't find any other report about this, which is really weird because it's really annoying. It probably means it's on my end (but I have absolutely no idea what can cause that).

If you have any ideas or suggestions !

Thanks again for your work (Also, I'm waiting for this !!! ==> #258 )

**Comment by vladimiry** [comment] 2020-09-09 16:54
> It probably means it's on my end

Not necessary. The first guess would be that something got recently changed at the protonmail's backend/API (like database queries processing got slowed down). The seconds guess is that protonmail introduced some delay in their web client for some reason (unlikely since it hurts UX, but technically possible).

I didn't really notice the issue since I primarily use the database view mode, not their UI/webclient.

Closing since there is nothing I could do at the app side to speed up described things, so upstream issue.

**Closed by vladimiry** 2020-09-09 16:54 UTC

**Comment by koopernick** [comment] 2020-09-09 17:43
I switched the API entry point (from "mail." to "api.") and it's working like a charm now.

Thank you for the idea !

**Comment by vladimiry** [comment] 2020-09-09 17:50
So then the issue is in their backend instance or if they run a single instance it might be that your network routing to original/"mail." domain got slowed down somehow (by your internet provider or at the upper level).
