### ISSUE TITLE
OR is missing as filter condition

### ISSUE THREAD

**Issue by edmundlaugasson** [vladimiry/ElectronMail#380] opened 2021-03-02 12:12 UTC
Currently impossible to use OR operator in filter options. In ProtonMail web interface it exist.
![Valik_241](https://user-images.githubusercontent.com/6355082/109646916-5dc27000-7b61-11eb-81f2-895f2a6c583a.png)

**Comment by vladimiry** [comment] 2021-03-02 12:17
This is correct. Not planned for implementing in the near future though. The workaround is to export all the emails to EML files (in the app can be done in 2 mouse clicks), then import them to any mature mail app or EML viewer and run the search there.

**Comment by vladimiry** [comment] 2021-03-02 12:22
Thanks placing the detailed issue. Closing as duplicate of #257.

**Comment by edmundlaugasson** [comment] 2021-03-02 12:22
For me the ONLY workaround in that case is to use ProtonMail web interface. Exporting all emails is a very bad "workaround". How is exporting emails and importing them into another email client and searching there related with email filtering, what we need in ProtonMail? IMHO it is inappropriate workaround. We need email filtering in ProtonMail and not kind of email search.

**Closed by vladimiry** 2021-03-02 12:22 UTC
Labels: enhancement, local store, workaround-exists

**Comment by vladimiry** [comment] 2021-03-02 12:24
Of course. Partial workaround then. I understand the need but my bandwidth is limited.
