### ISSUE TITLE
Tutanota - Remember Dark Mode

### ISSUE THREAD

**Issue by ghost** [vladimiry/ElectronMail#117] opened 2019-03-15 17:52 UTC
Every time I open email-securely-app, the Tutanota web client is rendered in light mode by default.  I would like an option to have it log into dark mode by default instead.  The "change theme" option is on Tutanota's login screen.  If I interrupt the sign-in process and switch to dark mode it works fine, but it doesn't remember this for next time I launch the program.

**Comment by vladimiry** [comment] 2019-03-17 10:18
Tutanota most likely saves the theme in the browser's cookies or local storage. The app by design goes with the in-memory session store.  So when you restart the app the previous session doesn't exist which means you get the default theme and other possible saved by Tutanota options.

There is no plan for enabling persistent sessions. Nevertheless, I believe it's feasible to intercept chosen theme value saving by the official web client and then saving it in app's config file instead (`config.json` file). Then the app, when it starts, would take the value and apply it. This would require to monkey patch the official web client.

Implementation of the described scenario is not going to happen in the near future. The issue gets low priority.

**Comment by vladimiry** [comment] 2019-03-17 10:37
> Every time I open email-securely-app

By the way, there is no email-securely-app anymore but ElectronMail. It's recommended to use the most recent app version.

**Comment by kzshantonu** [comment] 2019-06-15 00:01
Meanwhile I set 10 seconds 'login delay range' for tuta accounts so I can manually pick the theme while it counts down. Works perfectly

**Comment by vladimiry** [comment] 2019-06-15 06:06
Looks like you're getting to know the app features very well :+1:

**Comment by vladimiry** [comment] 2019-07-05 07:28
Closing due to #180.

**Closed by vladimiry** 2019-07-05 07:28 UTC
Labels: enhancement, webclient: monkey patch
